// Mocks generated by Mockito 5.4.6 from annotations
// in clothing_dashboard/test/helpers/mock_services.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i12;

import 'package:clothing_dashboard/core/models/employee_user.dart' as _i8;
import 'package:clothing_dashboard/core/models/models.dart' as _i5;
import 'package:clothing_dashboard/core/services/api_service.dart' as _i3;
import 'package:clothing_dashboard/core/services/client_api_service.dart'
    as _i6;
import 'package:clothing_dashboard/core/services/employee_api_service.dart'
    as _i7;
import 'package:clothing_dashboard/core/services/secure_storage_service.dart'
    as _i13;
import 'package:clothing_dashboard/core/services/storage_service.dart' as _i2;
import 'package:http/http.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:shared_preferences/shared_preferences.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStorageService_0 extends _i1.SmartFake
    implements _i2.StorageService {
  _FakeStorageService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiException_1 extends _i1.SmartFake implements _i3.ApiException {
  _FakeApiException_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_2<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResponse_3 extends _i1.SmartFake implements _i5.AuthResponse {
  _FakeAuthResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_4 extends _i1.SmartFake implements _i5.User {
  _FakeUser_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrdersResponse_5 extends _i1.SmartFake
    implements _i5.OrdersResponse {
  _FakeOrdersResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrder_6 extends _i1.SmartFake implements _i5.Order {
  _FakeOrder_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_7 extends _i1.SmartFake implements _i5.Client {
  _FakeClient_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrderModel_8 extends _i1.SmartFake implements _i5.OrderModel {
  _FakeOrderModel_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProcessStep_9 extends _i1.SmartFake implements _i5.ProcessStep {
  _FakeProcessStep_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEmployee_10 extends _i1.SmartFake implements _i5.Employee {
  _FakeEmployee_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkLog_11 extends _i1.SmartFake implements _i5.WorkLog {
  _FakeWorkLog_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayroll_12 extends _i1.SmartFake implements _i5.Payroll {
  _FakePayroll_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAnalyticsDashboard_13 extends _i1.SmartFake
    implements _i5.AnalyticsDashboard {
  _FakeAnalyticsDashboard_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDashboardStats_14 extends _i1.SmartFake
    implements _i5.DashboardStats {
  _FakeDashboardStats_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransaction_15 extends _i1.SmartFake implements _i5.Transaction {
  _FakeTransaction_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFinanceReport_16 extends _i1.SmartFake implements _i5.FinanceReport {
  _FakeFinanceReport_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForecast_17 extends _i1.SmartFake implements _i5.Forecast {
  _FakeForecast_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBusinessInsights_18 extends _i1.SmartFake
    implements _i5.BusinessInsights {
  _FakeBusinessInsights_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMlReport_19 extends _i1.SmartFake implements _i5.MlReport {
  _FakeMlReport_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMlUsageInfo_20 extends _i1.SmartFake implements _i5.MlUsageInfo {
  _FakeMlUsageInfo_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResourceUsage_21 extends _i1.SmartFake implements _i5.ResourceUsage {
  _FakeResourceUsage_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubscription_22 extends _i1.SmartFake implements _i5.Subscription {
  _FakeSubscription_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrderAssignment_23 extends _i1.SmartFake
    implements _i5.OrderAssignment {
  _FakeOrderAssignment_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientApiException_24 extends _i1.SmartFake
    implements _i6.ClientApiException {
  _FakeClientApiException_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientAuthResponse_25 extends _i1.SmartFake
    implements _i5.ClientAuthResponse {
  _FakeClientAuthResponse_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientUser_26 extends _i1.SmartFake implements _i5.ClientUser {
  _FakeClientUser_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTenantLink_27 extends _i1.SmartFake implements _i5.TenantLink {
  _FakeTenantLink_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientOrdersResponse_28 extends _i1.SmartFake
    implements _i5.ClientOrdersResponse {
  _FakeClientOrdersResponse_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientOrder_29 extends _i1.SmartFake implements _i5.ClientOrder {
  _FakeClientOrder_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEmployeeApiException_30 extends _i1.SmartFake
    implements _i7.EmployeeApiException {
  _FakeEmployeeApiException_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEmployeeAuthResponse_31 extends _i1.SmartFake
    implements _i8.EmployeeAuthResponse {
  _FakeEmployeeAuthResponse_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEmployeeUser_32 extends _i1.SmartFake implements _i8.EmployeeUser {
  _FakeEmployeeUser_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEmployeeAssignmentsResponse_33 extends _i1.SmartFake
    implements _i8.EmployeeAssignmentsResponse {
  _FakeEmployeeAssignmentsResponse_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEmployeeWorkLog_34 extends _i1.SmartFake
    implements _i8.EmployeeWorkLog {
  _FakeEmployeeWorkLog_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTokenHandler_35<T> extends _i1.SmartFake
    implements _i2.TokenHandler<T> {
  _FakeTokenHandler_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_36 extends _i1.SmartFake
    implements _i9.SharedPreferences {
  _FakeSharedPreferences_36(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get logPrefix => (super.noSuchMethod(
        Invocation.getter(#logPrefix),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#logPrefix),
        ),
      ) as String);

  @override
  String get authRefreshEndpoint => (super.noSuchMethod(
        Invocation.getter(#authRefreshEndpoint),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#authRefreshEndpoint),
        ),
      ) as String);

  @override
  _i2.StorageService get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeStorageService_0(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i2.StorageService);

  @override
  _i4.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> saveTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [
            accessToken,
            refreshToken,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i3.ApiException createException(
    String? message, {
    int? statusCode,
    dynamic data,
    bool? isNetworkError = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createException,
          [message],
          {
            #statusCode: statusCode,
            #data: data,
            #isNetworkError: isNetworkError,
          },
        ),
        returnValue: _FakeApiException_1(
          this,
          Invocation.method(
            #createException,
            [message],
            {
              #statusCode: statusCode,
              #data: data,
              #isNetworkError: isNetworkError,
            },
          ),
        ),
      ) as _i3.ApiException);

  @override
  void log(String? message) => super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<Map<String, String>> getHeaders({bool? auth = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHeaders,
          [],
          {#auth: auth},
        ),
        returnValue: _i4.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<T> withNetworkErrorHandling<T>(
          _i4.Future<T> Function()? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #withNetworkErrorHandling,
          [request],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #withNetworkErrorHandling,
                  [request],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #withNetworkErrorHandling,
                [request],
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<T> withRetry<T>(
    _i4.Future<T> Function()? request, {
    bool? isRetry = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #withRetry,
          [request],
          {#isRetry: isRetry},
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #withRetry,
                  [request],
                  {#isRetry: isRetry},
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #withRetry,
                [request],
                {#isRetry: isRetry},
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<bool> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<T> handleResponse<T>(
    _i11.Response? response,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleResponse,
          [
            response,
            fromJson,
          ],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #handleResponse,
                  [
                    response,
                    fromJson,
                  ],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #handleResponse,
                [
                  response,
                  fromJson,
                ],
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<List<T>> handleListResponse<T>(
    _i11.Response? response,
    T Function(Map<String, dynamic>)? fromJson, [
    String? key,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleListResponse,
          [
            response,
            fromJson,
            key,
          ],
        ),
        returnValue: _i4.Future<List<T>>.value(<T>[]),
      ) as _i4.Future<List<T>>);

  @override
  _i4.Future<List<T>> getListWithRetry<T>(
    _i4.Future<_i11.Response> Function()? request,
    T Function(Map<String, dynamic>)? fromJson,
    String? key, {
    bool? isRetry = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListWithRetry,
          [
            request,
            fromJson,
            key,
          ],
          {#isRetry: isRetry},
        ),
        returnValue: _i4.Future<List<T>>.value(<T>[]),
      ) as _i4.Future<List<T>>);

  @override
  _i4.Future<T> performLogin<T>({
    required String? endpoint,
    required Map<String, dynamic>? body,
    required T Function(Map<String, dynamic>)? fromJson,
    required _i4.Future<void> Function(T)? onSuccess,
    String? invalidCredentialsMessage = 'Неверный email или пароль',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performLogin,
          [],
          {
            #endpoint: endpoint,
            #body: body,
            #fromJson: fromJson,
            #onSuccess: onSuccess,
            #invalidCredentialsMessage: invalidCredentialsMessage,
          },
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #performLogin,
                  [],
                  {
                    #endpoint: endpoint,
                    #body: body,
                    #fromJson: fromJson,
                    #onSuccess: onSuccess,
                    #invalidCredentialsMessage: invalidCredentialsMessage,
                  },
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #performLogin,
                [],
                {
                  #endpoint: endpoint,
                  #body: body,
                  #fromJson: fromJson,
                  #onSuccess: onSuccess,
                  #invalidCredentialsMessage: invalidCredentialsMessage,
                },
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<void> performLogout({
    required String? endpoint,
    required _i4.Future<void> Function()? onComplete,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performLogout,
          [],
          {
            #endpoint: endpoint,
            #onComplete: onComplete,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.AuthResponse> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i5.AuthResponse>.value(_FakeAuthResponse_3(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i5.AuthResponse>);

  @override
  _i4.Future<_i5.AuthResponse> register(
    String? email,
    String? password,
    String? tenantName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            password,
            tenantName,
          ],
        ),
        returnValue: _i4.Future<_i5.AuthResponse>.value(_FakeAuthResponse_3(
          this,
          Invocation.method(
            #register,
            [
              email,
              password,
              tenantName,
            ],
          ),
        )),
      ) as _i4.Future<_i5.AuthResponse>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> changePassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [
            currentPassword,
            newPassword,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.User> uploadAvatar(_i12.File? file) => (super.noSuchMethod(
        Invocation.method(
          #uploadAvatar,
          [file],
        ),
        returnValue: _i4.Future<_i5.User>.value(_FakeUser_4(
          this,
          Invocation.method(
            #uploadAvatar,
            [file],
          ),
        )),
      ) as _i4.Future<_i5.User>);

  @override
  _i4.Future<_i5.User> deleteAvatar() => (super.noSuchMethod(
        Invocation.method(
          #deleteAvatar,
          [],
        ),
        returnValue: _i4.Future<_i5.User>.value(_FakeUser_4(
          this,
          Invocation.method(
            #deleteAvatar,
            [],
          ),
        )),
      ) as _i4.Future<_i5.User>);

  @override
  _i4.Future<_i5.OrdersResponse> getOrders({
    int? page = 1,
    int? limit = 20,
    String? status,
    String? sortBy,
    String? sortOrder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
          {
            #page: page,
            #limit: limit,
            #status: status,
            #sortBy: sortBy,
            #sortOrder: sortOrder,
          },
        ),
        returnValue: _i4.Future<_i5.OrdersResponse>.value(_FakeOrdersResponse_5(
          this,
          Invocation.method(
            #getOrders,
            [],
            {
              #page: page,
              #limit: limit,
              #status: status,
              #sortBy: sortBy,
              #sortOrder: sortOrder,
            },
          ),
        )),
      ) as _i4.Future<_i5.OrdersResponse>);

  @override
  _i4.Future<_i5.Order> getOrder(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getOrder,
          [id],
        ),
        returnValue: _i4.Future<_i5.Order>.value(_FakeOrder_6(
          this,
          Invocation.method(
            #getOrder,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.Order>);

  @override
  _i4.Future<_i5.Order> createOrder({
    required String? clientId,
    required String? modelId,
    required int? quantity,
    String? dueDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [],
          {
            #clientId: clientId,
            #modelId: modelId,
            #quantity: quantity,
            #dueDate: dueDate,
          },
        ),
        returnValue: _i4.Future<_i5.Order>.value(_FakeOrder_6(
          this,
          Invocation.method(
            #createOrder,
            [],
            {
              #clientId: clientId,
              #modelId: modelId,
              #quantity: quantity,
              #dueDate: dueDate,
            },
          ),
        )),
      ) as _i4.Future<_i5.Order>);

  @override
  _i4.Future<_i5.Order> updateOrderStatus(
    String? id,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderStatus,
          [
            id,
            status,
          ],
        ),
        returnValue: _i4.Future<_i5.Order>.value(_FakeOrder_6(
          this,
          Invocation.method(
            #updateOrderStatus,
            [
              id,
              status,
            ],
          ),
        )),
      ) as _i4.Future<_i5.Order>);

  @override
  _i4.Future<Map<String, dynamic>?> searchClientUserByEmail(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchClientUserByEmail,
          [email],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<_i5.Client>> getClients({
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClients,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i5.Client>>.value(<_i5.Client>[]),
      ) as _i4.Future<List<_i5.Client>>);

  @override
  _i4.Future<_i5.Client> getClient(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getClient,
          [id],
        ),
        returnValue: _i4.Future<_i5.Client>.value(_FakeClient_7(
          this,
          Invocation.method(
            #getClient,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.Client>);

  @override
  _i4.Future<_i5.Client> createClient({
    required String? name,
    String? email,
    String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createClient,
          [],
          {
            #name: name,
            #email: email,
            #phone: phone,
          },
        ),
        returnValue: _i4.Future<_i5.Client>.value(_FakeClient_7(
          this,
          Invocation.method(
            #createClient,
            [],
            {
              #name: name,
              #email: email,
              #phone: phone,
            },
          ),
        )),
      ) as _i4.Future<_i5.Client>);

  @override
  _i4.Future<_i5.Client> updateClient({
    required String? id,
    String? name,
    String? phone,
    String? email,
    String? telegram,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateClient,
          [],
          {
            #id: id,
            #name: name,
            #phone: phone,
            #email: email,
            #telegram: telegram,
            #notes: notes,
          },
        ),
        returnValue: _i4.Future<_i5.Client>.value(_FakeClient_7(
          this,
          Invocation.method(
            #updateClient,
            [],
            {
              #id: id,
              #name: name,
              #phone: phone,
              #email: email,
              #telegram: telegram,
              #notes: notes,
            },
          ),
        )),
      ) as _i4.Future<_i5.Client>);

  @override
  _i4.Future<void> deleteClient(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteClient,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.OrderModel>> getClientAssignedModels(String? clientId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClientAssignedModels,
          [clientId],
        ),
        returnValue: _i4.Future<List<_i5.OrderModel>>.value(<_i5.OrderModel>[]),
      ) as _i4.Future<List<_i5.OrderModel>>);

  @override
  _i4.Future<_i5.Client> assignModelsToClient(
    String? clientId,
    List<String>? modelIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignModelsToClient,
          [
            clientId,
            modelIds,
          ],
        ),
        returnValue: _i4.Future<_i5.Client>.value(_FakeClient_7(
          this,
          Invocation.method(
            #assignModelsToClient,
            [
              clientId,
              modelIds,
            ],
          ),
        )),
      ) as _i4.Future<_i5.Client>);

  @override
  _i4.Future<_i5.Client> setClientAssignedModels(
    String? clientId,
    List<String>? modelIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setClientAssignedModels,
          [
            clientId,
            modelIds,
          ],
        ),
        returnValue: _i4.Future<_i5.Client>.value(_FakeClient_7(
          this,
          Invocation.method(
            #setClientAssignedModels,
            [
              clientId,
              modelIds,
            ],
          ),
        )),
      ) as _i4.Future<_i5.Client>);

  @override
  _i4.Future<_i5.Client> unassignModelFromClient(
    String? clientId,
    String? modelId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unassignModelFromClient,
          [
            clientId,
            modelId,
          ],
        ),
        returnValue: _i4.Future<_i5.Client>.value(_FakeClient_7(
          this,
          Invocation.method(
            #unassignModelFromClient,
            [
              clientId,
              modelId,
            ],
          ),
        )),
      ) as _i4.Future<_i5.Client>);

  @override
  _i4.Future<List<_i5.OrderModel>> getModels({
    int? page = 1,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModels,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i5.OrderModel>>.value(<_i5.OrderModel>[]),
      ) as _i4.Future<List<_i5.OrderModel>>);

  @override
  _i4.Future<_i5.OrderModel> getModel(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getModel,
          [id],
        ),
        returnValue: _i4.Future<_i5.OrderModel>.value(_FakeOrderModel_8(
          this,
          Invocation.method(
            #getModel,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.OrderModel>);

  @override
  _i4.Future<_i5.OrderModel> createModel({
    required String? name,
    String? category,
    required double? basePrice,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createModel,
          [],
          {
            #name: name,
            #category: category,
            #basePrice: basePrice,
            #description: description,
          },
        ),
        returnValue: _i4.Future<_i5.OrderModel>.value(_FakeOrderModel_8(
          this,
          Invocation.method(
            #createModel,
            [],
            {
              #name: name,
              #category: category,
              #basePrice: basePrice,
              #description: description,
            },
          ),
        )),
      ) as _i4.Future<_i5.OrderModel>);

  @override
  _i4.Future<_i5.OrderModel> updateModel({
    required String? id,
    String? name,
    String? category,
    double? basePrice,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateModel,
          [],
          {
            #id: id,
            #name: name,
            #category: category,
            #basePrice: basePrice,
            #description: description,
          },
        ),
        returnValue: _i4.Future<_i5.OrderModel>.value(_FakeOrderModel_8(
          this,
          Invocation.method(
            #updateModel,
            [],
            {
              #id: id,
              #name: name,
              #category: category,
              #basePrice: basePrice,
              #description: description,
            },
          ),
        )),
      ) as _i4.Future<_i5.OrderModel>);

  @override
  _i4.Future<void> deleteModel(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteModel,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.OrderModel> uploadModelImage(
    String? modelId,
    _i12.File? file,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadModelImage,
          [
            modelId,
            file,
          ],
        ),
        returnValue: _i4.Future<_i5.OrderModel>.value(_FakeOrderModel_8(
          this,
          Invocation.method(
            #uploadModelImage,
            [
              modelId,
              file,
            ],
          ),
        )),
      ) as _i4.Future<_i5.OrderModel>);

  @override
  _i4.Future<_i5.OrderModel> deleteModelImage(String? modelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteModelImage,
          [modelId],
        ),
        returnValue: _i4.Future<_i5.OrderModel>.value(_FakeOrderModel_8(
          this,
          Invocation.method(
            #deleteModelImage,
            [modelId],
          ),
        )),
      ) as _i4.Future<_i5.OrderModel>);

  @override
  _i4.Future<List<_i5.ProcessStep>> getProcessSteps(String? modelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProcessSteps,
          [modelId],
        ),
        returnValue:
            _i4.Future<List<_i5.ProcessStep>>.value(<_i5.ProcessStep>[]),
      ) as _i4.Future<List<_i5.ProcessStep>>);

  @override
  _i4.Future<_i5.ProcessStep> createProcessStep({
    required String? modelId,
    required int? stepOrder,
    required String? name,
    required int? estimatedTime,
    required String? executorRole,
    double? rate,
    String? rateType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProcessStep,
          [],
          {
            #modelId: modelId,
            #stepOrder: stepOrder,
            #name: name,
            #estimatedTime: estimatedTime,
            #executorRole: executorRole,
            #rate: rate,
            #rateType: rateType,
          },
        ),
        returnValue: _i4.Future<_i5.ProcessStep>.value(_FakeProcessStep_9(
          this,
          Invocation.method(
            #createProcessStep,
            [],
            {
              #modelId: modelId,
              #stepOrder: stepOrder,
              #name: name,
              #estimatedTime: estimatedTime,
              #executorRole: executorRole,
              #rate: rate,
              #rateType: rateType,
            },
          ),
        )),
      ) as _i4.Future<_i5.ProcessStep>);

  @override
  _i4.Future<_i5.ProcessStep> updateProcessStep({
    required String? stepId,
    int? stepOrder,
    String? name,
    int? estimatedTime,
    String? executorRole,
    double? rate,
    String? rateType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProcessStep,
          [],
          {
            #stepId: stepId,
            #stepOrder: stepOrder,
            #name: name,
            #estimatedTime: estimatedTime,
            #executorRole: executorRole,
            #rate: rate,
            #rateType: rateType,
          },
        ),
        returnValue: _i4.Future<_i5.ProcessStep>.value(_FakeProcessStep_9(
          this,
          Invocation.method(
            #updateProcessStep,
            [],
            {
              #stepId: stepId,
              #stepOrder: stepOrder,
              #name: name,
              #estimatedTime: estimatedTime,
              #executorRole: executorRole,
              #rate: rate,
              #rateType: rateType,
            },
          ),
        )),
      ) as _i4.Future<_i5.ProcessStep>);

  @override
  _i4.Future<void> deleteProcessStep(String? stepId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProcessStep,
          [stepId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.EmployeeRole>> getEmployeeRoles() => (super.noSuchMethod(
        Invocation.method(
          #getEmployeeRoles,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.EmployeeRole>>.value(<_i5.EmployeeRole>[]),
      ) as _i4.Future<List<_i5.EmployeeRole>>);

  @override
  _i4.Future<List<_i5.Employee>> getEmployees({
    int? page = 1,
    int? limit = 50,
    bool? isActive,
    String? role,
    String? sortBy,
    String? sortOrder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEmployees,
          [],
          {
            #page: page,
            #limit: limit,
            #isActive: isActive,
            #role: role,
            #sortBy: sortBy,
            #sortOrder: sortOrder,
          },
        ),
        returnValue: _i4.Future<List<_i5.Employee>>.value(<_i5.Employee>[]),
      ) as _i4.Future<List<_i5.Employee>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getEmployeeWorkLogs(
    String? employeeId, {
    String? dateFrom,
    String? dateTo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEmployeeWorkLogs,
          [employeeId],
          {
            #dateFrom: dateFrom,
            #dateTo: dateTo,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllWorklogs({
    String? employeeId,
    String? dateFrom,
    String? dateTo,
    String? step,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllWorklogs,
          [],
          {
            #employeeId: employeeId,
            #dateFrom: dateFrom,
            #dateTo: dateTo,
            #step: step,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> getWorklogsSummary({
    String? employeeId,
    String? dateFrom,
    String? dateTo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorklogsSummary,
          [],
          {
            #employeeId: employeeId,
            #dateFrom: dateFrom,
            #dateTo: dateTo,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i5.Employee> getEmployee(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getEmployee,
          [id],
        ),
        returnValue: _i4.Future<_i5.Employee>.value(_FakeEmployee_10(
          this,
          Invocation.method(
            #getEmployee,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.Employee>);

  @override
  _i4.Future<_i5.Employee> createEmployee({
    required String? name,
    required String? role,
    String? phone,
    String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEmployee,
          [],
          {
            #name: name,
            #role: role,
            #phone: phone,
            #email: email,
          },
        ),
        returnValue: _i4.Future<_i5.Employee>.value(_FakeEmployee_10(
          this,
          Invocation.method(
            #createEmployee,
            [],
            {
              #name: name,
              #role: role,
              #phone: phone,
              #email: email,
            },
          ),
        )),
      ) as _i4.Future<_i5.Employee>);

  @override
  _i4.Future<_i5.Employee> updateEmployee({
    required String? id,
    String? name,
    String? role,
    String? phone,
    String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEmployee,
          [],
          {
            #id: id,
            #name: name,
            #role: role,
            #phone: phone,
            #email: email,
          },
        ),
        returnValue: _i4.Future<_i5.Employee>.value(_FakeEmployee_10(
          this,
          Invocation.method(
            #updateEmployee,
            [],
            {
              #id: id,
              #name: name,
              #role: role,
              #phone: phone,
              #email: email,
            },
          ),
        )),
      ) as _i4.Future<_i5.Employee>);

  @override
  _i4.Future<void> deleteEmployee(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEmployee,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.WorkLog>> getWorkLogs() => (super.noSuchMethod(
        Invocation.method(
          #getWorkLogs,
          [],
        ),
        returnValue: _i4.Future<List<_i5.WorkLog>>.value(<_i5.WorkLog>[]),
      ) as _i4.Future<List<_i5.WorkLog>>);

  @override
  _i4.Future<_i5.WorkLog> createWorkLog({
    required String? employeeId,
    required String? orderId,
    required String? step,
    required int? quantity,
    required double? hours,
    required DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkLog,
          [],
          {
            #employeeId: employeeId,
            #orderId: orderId,
            #step: step,
            #quantity: quantity,
            #hours: hours,
            #date: date,
          },
        ),
        returnValue: _i4.Future<_i5.WorkLog>.value(_FakeWorkLog_11(
          this,
          Invocation.method(
            #createWorkLog,
            [],
            {
              #employeeId: employeeId,
              #orderId: orderId,
              #step: step,
              #quantity: quantity,
              #hours: hours,
              #date: date,
            },
          ),
        )),
      ) as _i4.Future<_i5.WorkLog>);

  @override
  _i4.Future<List<_i5.Payroll>> getPayrolls() => (super.noSuchMethod(
        Invocation.method(
          #getPayrolls,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Payroll>>.value(<_i5.Payroll>[]),
      ) as _i4.Future<List<_i5.Payroll>>);

  @override
  _i4.Future<_i5.Payroll> generatePayroll({
    required DateTime? periodStart,
    required DateTime? periodEnd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generatePayroll,
          [],
          {
            #periodStart: periodStart,
            #periodEnd: periodEnd,
          },
        ),
        returnValue: _i4.Future<_i5.Payroll>.value(_FakePayroll_12(
          this,
          Invocation.method(
            #generatePayroll,
            [],
            {
              #periodStart: periodStart,
              #periodEnd: periodEnd,
            },
          ),
        )),
      ) as _i4.Future<_i5.Payroll>);

  @override
  _i4.Future<_i5.AnalyticsDashboard> getAnalyticsDashboard(
          {String? period = 'month'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAnalyticsDashboard,
          [],
          {#period: period},
        ),
        returnValue:
            _i4.Future<_i5.AnalyticsDashboard>.value(_FakeAnalyticsDashboard_13(
          this,
          Invocation.method(
            #getAnalyticsDashboard,
            [],
            {#period: period},
          ),
        )),
      ) as _i4.Future<_i5.AnalyticsDashboard>);

  @override
  _i4.Future<_i5.DashboardStats> getDashboardStats(
          {String? period = 'month'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDashboardStats,
          [],
          {#period: period},
        ),
        returnValue:
            _i4.Future<_i5.DashboardStats>.value(_FakeDashboardStats_14(
          this,
          Invocation.method(
            #getDashboardStats,
            [],
            {#period: period},
          ),
        )),
      ) as _i4.Future<_i5.DashboardStats>);

  @override
  _i4.Future<Map<String, dynamic>> getWorkloadCalendar({
    int? days = 14,
    String? employeeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkloadCalendar,
          [],
          {
            #days: days,
            #employeeId: employeeId,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i5.Transaction>> getTransactions({
    String? type,
    String? startDate,
    String? endDate,
    int? page = 1,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [],
          {
            #type: type,
            #startDate: startDate,
            #endDate: endDate,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i5.Transaction>>.value(<_i5.Transaction>[]),
      ) as _i4.Future<List<_i5.Transaction>>);

  @override
  _i4.Future<_i5.Transaction> createTransaction({
    required DateTime? date,
    required String? type,
    required String? category,
    required double? amount,
    String? description,
    String? orderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTransaction,
          [],
          {
            #date: date,
            #type: type,
            #category: category,
            #amount: amount,
            #description: description,
            #orderId: orderId,
          },
        ),
        returnValue: _i4.Future<_i5.Transaction>.value(_FakeTransaction_15(
          this,
          Invocation.method(
            #createTransaction,
            [],
            {
              #date: date,
              #type: type,
              #category: category,
              #amount: amount,
              #description: description,
              #orderId: orderId,
            },
          ),
        )),
      ) as _i4.Future<_i5.Transaction>);

  @override
  _i4.Future<void> deleteTransaction(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTransaction,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.FinanceReport> getFinanceReport({
    String? startDate,
    String? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFinanceReport,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i4.Future<_i5.FinanceReport>.value(_FakeFinanceReport_16(
          this,
          Invocation.method(
            #getFinanceReport,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i5.FinanceReport>);

  @override
  _i4.Future<_i5.Forecast> getOrdersForecast({int? days = 7}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrdersForecast,
          [],
          {#days: days},
        ),
        returnValue: _i4.Future<_i5.Forecast>.value(_FakeForecast_17(
          this,
          Invocation.method(
            #getOrdersForecast,
            [],
            {#days: days},
          ),
        )),
      ) as _i4.Future<_i5.Forecast>);

  @override
  _i4.Future<_i5.Forecast> getRevenueForecast({int? days = 7}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRevenueForecast,
          [],
          {#days: days},
        ),
        returnValue: _i4.Future<_i5.Forecast>.value(_FakeForecast_17(
          this,
          Invocation.method(
            #getRevenueForecast,
            [],
            {#days: days},
          ),
        )),
      ) as _i4.Future<_i5.Forecast>);

  @override
  _i4.Future<_i5.BusinessInsights> getBusinessInsights() => (super.noSuchMethod(
        Invocation.method(
          #getBusinessInsights,
          [],
        ),
        returnValue:
            _i4.Future<_i5.BusinessInsights>.value(_FakeBusinessInsights_18(
          this,
          Invocation.method(
            #getBusinessInsights,
            [],
          ),
        )),
      ) as _i4.Future<_i5.BusinessInsights>);

  @override
  _i4.Future<_i5.MlReport> generateMlReport({
    required String? type,
    String? periodStart,
    String? periodEnd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateMlReport,
          [],
          {
            #type: type,
            #periodStart: periodStart,
            #periodEnd: periodEnd,
          },
        ),
        returnValue: _i4.Future<_i5.MlReport>.value(_FakeMlReport_19(
          this,
          Invocation.method(
            #generateMlReport,
            [],
            {
              #type: type,
              #periodStart: periodStart,
              #periodEnd: periodEnd,
            },
          ),
        )),
      ) as _i4.Future<_i5.MlReport>);

  @override
  _i4.Future<List<_i5.MlReport>> getReportHistory({
    String? type,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReportHistory,
          [],
          {
            #type: type,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i5.MlReport>>.value(<_i5.MlReport>[]),
      ) as _i4.Future<List<_i5.MlReport>>);

  @override
  _i4.Future<_i5.MlUsageInfo> getMlUsageInfo() => (super.noSuchMethod(
        Invocation.method(
          #getMlUsageInfo,
          [],
        ),
        returnValue: _i4.Future<_i5.MlUsageInfo>.value(_FakeMlUsageInfo_20(
          this,
          Invocation.method(
            #getMlUsageInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i5.MlUsageInfo>);

  @override
  _i4.Future<List<_i5.SubscriptionPlan>> getSubscriptionPlans() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubscriptionPlans,
          [],
        ),
        returnValue: _i4.Future<List<_i5.SubscriptionPlan>>.value(
            <_i5.SubscriptionPlan>[]),
      ) as _i4.Future<List<_i5.SubscriptionPlan>>);

  @override
  _i4.Future<_i5.ResourceUsage> getResourceUsage() => (super.noSuchMethod(
        Invocation.method(
          #getResourceUsage,
          [],
        ),
        returnValue: _i4.Future<_i5.ResourceUsage>.value(_FakeResourceUsage_21(
          this,
          Invocation.method(
            #getResourceUsage,
            [],
          ),
        )),
      ) as _i4.Future<_i5.ResourceUsage>);

  @override
  _i4.Future<_i5.Subscription?> getCurrentSubscription() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentSubscription,
          [],
        ),
        returnValue: _i4.Future<_i5.Subscription?>.value(),
      ) as _i4.Future<_i5.Subscription?>);

  @override
  _i4.Future<_i5.Subscription> verifyGooglePlayPurchase({
    required String? productId,
    required String? purchaseToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyGooglePlayPurchase,
          [],
          {
            #productId: productId,
            #purchaseToken: purchaseToken,
          },
        ),
        returnValue: _i4.Future<_i5.Subscription>.value(_FakeSubscription_22(
          this,
          Invocation.method(
            #verifyGooglePlayPurchase,
            [],
            {
              #productId: productId,
              #purchaseToken: purchaseToken,
            },
          ),
        )),
      ) as _i4.Future<_i5.Subscription>);

  @override
  _i4.Future<_i5.Subscription> verifyAppStorePurchase(
          {required String? receiptData}) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyAppStorePurchase,
          [],
          {#receiptData: receiptData},
        ),
        returnValue: _i4.Future<_i5.Subscription>.value(_FakeSubscription_22(
          this,
          Invocation.method(
            #verifyAppStorePurchase,
            [],
            {#receiptData: receiptData},
          ),
        )),
      ) as _i4.Future<_i5.Subscription>);

  @override
  _i4.Future<void> registerPushDevice(String? playerId) => (super.noSuchMethod(
        Invocation.method(
          #registerPushDevice,
          [playerId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unregisterPushDevice() => (super.noSuchMethod(
        Invocation.method(
          #unregisterPushDevice,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.OrderAssignment>> getOrderAssignments(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderAssignments,
          [orderId],
        ),
        returnValue: _i4.Future<List<_i5.OrderAssignment>>.value(
            <_i5.OrderAssignment>[]),
      ) as _i4.Future<List<_i5.OrderAssignment>>);

  @override
  _i4.Future<_i5.OrderAssignment> createOrderAssignment({
    required String? orderId,
    required String? stepName,
    required String? employeeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrderAssignment,
          [],
          {
            #orderId: orderId,
            #stepName: stepName,
            #employeeId: employeeId,
          },
        ),
        returnValue:
            _i4.Future<_i5.OrderAssignment>.value(_FakeOrderAssignment_23(
          this,
          Invocation.method(
            #createOrderAssignment,
            [],
            {
              #orderId: orderId,
              #stepName: stepName,
              #employeeId: employeeId,
            },
          ),
        )),
      ) as _i4.Future<_i5.OrderAssignment>);

  @override
  _i4.Future<void> deleteOrderAssignment(
    String? orderId,
    String? assignmentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrderAssignment,
          [
            orderId,
            assignmentId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ClientApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientApiService extends _i1.Mock implements _i6.ClientApiService {
  MockClientApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get logPrefix => (super.noSuchMethod(
        Invocation.getter(#logPrefix),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#logPrefix),
        ),
      ) as String);

  @override
  String get authRefreshEndpoint => (super.noSuchMethod(
        Invocation.getter(#authRefreshEndpoint),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#authRefreshEndpoint),
        ),
      ) as String);

  @override
  _i2.StorageService get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeStorageService_0(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i2.StorageService);

  @override
  _i4.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> saveTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [
            accessToken,
            refreshToken,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i6.ClientApiException createException(
    String? message, {
    int? statusCode,
    dynamic data,
    bool? isNetworkError = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createException,
          [message],
          {
            #statusCode: statusCode,
            #data: data,
            #isNetworkError: isNetworkError,
          },
        ),
        returnValue: _FakeClientApiException_24(
          this,
          Invocation.method(
            #createException,
            [message],
            {
              #statusCode: statusCode,
              #data: data,
              #isNetworkError: isNetworkError,
            },
          ),
        ),
      ) as _i6.ClientApiException);

  @override
  _i4.Future<_i5.ClientAuthResponse> login({
    String? email,
    String? phone,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #phone: phone,
            #password: password,
          },
        ),
        returnValue:
            _i4.Future<_i5.ClientAuthResponse>.value(_FakeClientAuthResponse_25(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i5.ClientAuthResponse>);

  @override
  _i4.Future<_i5.ClientAuthResponse> register({
    String? email,
    String? phone,
    required String? password,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #email: email,
            #phone: phone,
            #password: password,
            #name: name,
          },
        ),
        returnValue:
            _i4.Future<_i5.ClientAuthResponse>.value(_FakeClientAuthResponse_25(
          this,
          Invocation.method(
            #register,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
              #name: name,
            },
          ),
        )),
      ) as _i4.Future<_i5.ClientAuthResponse>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.ClientUser> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i4.Future<_i5.ClientUser>.value(_FakeClientUser_26(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i4.Future<_i5.ClientUser>);

  @override
  _i4.Future<List<_i5.TenantLink>> getMyTenants() => (super.noSuchMethod(
        Invocation.method(
          #getMyTenants,
          [],
        ),
        returnValue: _i4.Future<List<_i5.TenantLink>>.value(<_i5.TenantLink>[]),
      ) as _i4.Future<List<_i5.TenantLink>>);

  @override
  _i4.Future<_i5.TenantLink> linkToTenant(
    String? tenantId, {
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkToTenant,
          [tenantId],
          {#name: name},
        ),
        returnValue: _i4.Future<_i5.TenantLink>.value(_FakeTenantLink_27(
          this,
          Invocation.method(
            #linkToTenant,
            [tenantId],
            {#name: name},
          ),
        )),
      ) as _i4.Future<_i5.TenantLink>);

  @override
  _i4.Future<List<_i5.ClientOrderModel>> getTenantModels(String? tenantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTenantModels,
          [tenantId],
        ),
        returnValue: _i4.Future<List<_i5.ClientOrderModel>>.value(
            <_i5.ClientOrderModel>[]),
      ) as _i4.Future<List<_i5.ClientOrderModel>>);

  @override
  _i4.Future<_i5.ClientOrdersResponse> getMyOrders({
    String? tenantId,
    int? page = 1,
    int? limit = 20,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyOrders,
          [],
          {
            #tenantId: tenantId,
            #page: page,
            #limit: limit,
            #status: status,
          },
        ),
        returnValue: _i4.Future<_i5.ClientOrdersResponse>.value(
            _FakeClientOrdersResponse_28(
          this,
          Invocation.method(
            #getMyOrders,
            [],
            {
              #tenantId: tenantId,
              #page: page,
              #limit: limit,
              #status: status,
            },
          ),
        )),
      ) as _i4.Future<_i5.ClientOrdersResponse>);

  @override
  _i4.Future<_i5.ClientOrder> getOrder(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #getOrder,
          [orderId],
        ),
        returnValue: _i4.Future<_i5.ClientOrder>.value(_FakeClientOrder_29(
          this,
          Invocation.method(
            #getOrder,
            [orderId],
          ),
        )),
      ) as _i4.Future<_i5.ClientOrder>);

  @override
  _i4.Future<_i5.ClientOrder> createOrder({
    required String? tenantId,
    required String? modelId,
    required int? quantity,
    String? dueDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [],
          {
            #tenantId: tenantId,
            #modelId: modelId,
            #quantity: quantity,
            #dueDate: dueDate,
          },
        ),
        returnValue: _i4.Future<_i5.ClientOrder>.value(_FakeClientOrder_29(
          this,
          Invocation.method(
            #createOrder,
            [],
            {
              #tenantId: tenantId,
              #modelId: modelId,
              #quantity: quantity,
              #dueDate: dueDate,
            },
          ),
        )),
      ) as _i4.Future<_i5.ClientOrder>);

  @override
  _i4.Future<_i5.ClientOrder> updateOrder({
    required String? orderId,
    String? modelId,
    int? quantity,
    String? dueDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrder,
          [],
          {
            #orderId: orderId,
            #modelId: modelId,
            #quantity: quantity,
            #dueDate: dueDate,
          },
        ),
        returnValue: _i4.Future<_i5.ClientOrder>.value(_FakeClientOrder_29(
          this,
          Invocation.method(
            #updateOrder,
            [],
            {
              #orderId: orderId,
              #modelId: modelId,
              #quantity: quantity,
              #dueDate: dueDate,
            },
          ),
        )),
      ) as _i4.Future<_i5.ClientOrder>);

  @override
  _i4.Future<void> cancelOrder(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #cancelOrder,
          [orderId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void log(String? message) => super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<Map<String, String>> getHeaders({bool? auth = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHeaders,
          [],
          {#auth: auth},
        ),
        returnValue: _i4.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<T> withNetworkErrorHandling<T>(
          _i4.Future<T> Function()? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #withNetworkErrorHandling,
          [request],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #withNetworkErrorHandling,
                  [request],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #withNetworkErrorHandling,
                [request],
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<T> withRetry<T>(
    _i4.Future<T> Function()? request, {
    bool? isRetry = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #withRetry,
          [request],
          {#isRetry: isRetry},
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #withRetry,
                  [request],
                  {#isRetry: isRetry},
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #withRetry,
                [request],
                {#isRetry: isRetry},
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<bool> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<T> handleResponse<T>(
    _i11.Response? response,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleResponse,
          [
            response,
            fromJson,
          ],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #handleResponse,
                  [
                    response,
                    fromJson,
                  ],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #handleResponse,
                [
                  response,
                  fromJson,
                ],
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<List<T>> handleListResponse<T>(
    _i11.Response? response,
    T Function(Map<String, dynamic>)? fromJson, [
    String? key,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleListResponse,
          [
            response,
            fromJson,
            key,
          ],
        ),
        returnValue: _i4.Future<List<T>>.value(<T>[]),
      ) as _i4.Future<List<T>>);

  @override
  _i4.Future<List<T>> getListWithRetry<T>(
    _i4.Future<_i11.Response> Function()? request,
    T Function(Map<String, dynamic>)? fromJson,
    String? key, {
    bool? isRetry = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListWithRetry,
          [
            request,
            fromJson,
            key,
          ],
          {#isRetry: isRetry},
        ),
        returnValue: _i4.Future<List<T>>.value(<T>[]),
      ) as _i4.Future<List<T>>);

  @override
  _i4.Future<T> performLogin<T>({
    required String? endpoint,
    required Map<String, dynamic>? body,
    required T Function(Map<String, dynamic>)? fromJson,
    required _i4.Future<void> Function(T)? onSuccess,
    String? invalidCredentialsMessage = 'Неверный email или пароль',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performLogin,
          [],
          {
            #endpoint: endpoint,
            #body: body,
            #fromJson: fromJson,
            #onSuccess: onSuccess,
            #invalidCredentialsMessage: invalidCredentialsMessage,
          },
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #performLogin,
                  [],
                  {
                    #endpoint: endpoint,
                    #body: body,
                    #fromJson: fromJson,
                    #onSuccess: onSuccess,
                    #invalidCredentialsMessage: invalidCredentialsMessage,
                  },
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #performLogin,
                [],
                {
                  #endpoint: endpoint,
                  #body: body,
                  #fromJson: fromJson,
                  #onSuccess: onSuccess,
                  #invalidCredentialsMessage: invalidCredentialsMessage,
                },
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<void> performLogout({
    required String? endpoint,
    required _i4.Future<void> Function()? onComplete,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performLogout,
          [],
          {
            #endpoint: endpoint,
            #onComplete: onComplete,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [EmployeeApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmployeeApiService extends _i1.Mock
    implements _i7.EmployeeApiService {
  MockEmployeeApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get logPrefix => (super.noSuchMethod(
        Invocation.getter(#logPrefix),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#logPrefix),
        ),
      ) as String);

  @override
  String get authRefreshEndpoint => (super.noSuchMethod(
        Invocation.getter(#authRefreshEndpoint),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#authRefreshEndpoint),
        ),
      ) as String);

  @override
  _i2.StorageService get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeStorageService_0(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i2.StorageService);

  @override
  _i4.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> saveTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [
            accessToken,
            refreshToken,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i7.EmployeeApiException createException(
    String? message, {
    int? statusCode,
    dynamic data,
    bool? isNetworkError = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createException,
          [message],
          {
            #statusCode: statusCode,
            #data: data,
            #isNetworkError: isNetworkError,
          },
        ),
        returnValue: _FakeEmployeeApiException_30(
          this,
          Invocation.method(
            #createException,
            [message],
            {
              #statusCode: statusCode,
              #data: data,
              #isNetworkError: isNetworkError,
            },
          ),
        ),
      ) as _i7.EmployeeApiException);

  @override
  _i4.Future<_i8.EmployeeAuthResponse> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i8.EmployeeAuthResponse>.value(
            _FakeEmployeeAuthResponse_31(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i8.EmployeeAuthResponse>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i8.EmployeeUser> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i4.Future<_i8.EmployeeUser>.value(_FakeEmployeeUser_32(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i4.Future<_i8.EmployeeUser>);

  @override
  _i4.Future<_i8.EmployeeAssignmentsResponse> getAssignments({
    int? page = 1,
    int? limit = 20,
    bool? includeCompleted = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignments,
          [],
          {
            #page: page,
            #limit: limit,
            #includeCompleted: includeCompleted,
          },
        ),
        returnValue: _i4.Future<_i8.EmployeeAssignmentsResponse>.value(
            _FakeEmployeeAssignmentsResponse_33(
          this,
          Invocation.method(
            #getAssignments,
            [],
            {
              #page: page,
              #limit: limit,
              #includeCompleted: includeCompleted,
            },
          ),
        )),
      ) as _i4.Future<_i8.EmployeeAssignmentsResponse>);

  @override
  _i4.Future<Map<String, dynamic>> getAssignmentById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssignmentById,
          [id],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i8.EmployeeWorkLog> createWorkLog(
          _i8.CreateWorkLogRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkLog,
          [request],
        ),
        returnValue:
            _i4.Future<_i8.EmployeeWorkLog>.value(_FakeEmployeeWorkLog_34(
          this,
          Invocation.method(
            #createWorkLog,
            [request],
          ),
        )),
      ) as _i4.Future<_i8.EmployeeWorkLog>);

  @override
  _i4.Future<Map<String, dynamic>?> getWorkLogByDate(
    String? assignmentId,
    String? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkLogByDate,
          [
            assignmentId,
            date,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<_i8.EmployeeWorkLog>> getWorkLogs({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkLogs,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i4.Future<List<_i8.EmployeeWorkLog>>.value(
            <_i8.EmployeeWorkLog>[]),
      ) as _i4.Future<List<_i8.EmployeeWorkLog>>);

  @override
  _i4.Future<List<_i8.EmployeePayroll>> getPayrolls() => (super.noSuchMethod(
        Invocation.method(
          #getPayrolls,
          [],
        ),
        returnValue: _i4.Future<List<_i8.EmployeePayroll>>.value(
            <_i8.EmployeePayroll>[]),
      ) as _i4.Future<List<_i8.EmployeePayroll>>);

  @override
  _i4.Future<void> registerPushDevice(String? playerId) => (super.noSuchMethod(
        Invocation.method(
          #registerPushDevice,
          [playerId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unregisterPushDevice() => (super.noSuchMethod(
        Invocation.method(
          #unregisterPushDevice,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void log(String? message) => super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<Map<String, String>> getHeaders({bool? auth = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHeaders,
          [],
          {#auth: auth},
        ),
        returnValue: _i4.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<T> withNetworkErrorHandling<T>(
          _i4.Future<T> Function()? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #withNetworkErrorHandling,
          [request],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #withNetworkErrorHandling,
                  [request],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #withNetworkErrorHandling,
                [request],
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<T> withRetry<T>(
    _i4.Future<T> Function()? request, {
    bool? isRetry = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #withRetry,
          [request],
          {#isRetry: isRetry},
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #withRetry,
                  [request],
                  {#isRetry: isRetry},
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #withRetry,
                [request],
                {#isRetry: isRetry},
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<bool> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<T> handleResponse<T>(
    _i11.Response? response,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleResponse,
          [
            response,
            fromJson,
          ],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #handleResponse,
                  [
                    response,
                    fromJson,
                  ],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #handleResponse,
                [
                  response,
                  fromJson,
                ],
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<List<T>> handleListResponse<T>(
    _i11.Response? response,
    T Function(Map<String, dynamic>)? fromJson, [
    String? key,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleListResponse,
          [
            response,
            fromJson,
            key,
          ],
        ),
        returnValue: _i4.Future<List<T>>.value(<T>[]),
      ) as _i4.Future<List<T>>);

  @override
  _i4.Future<List<T>> getListWithRetry<T>(
    _i4.Future<_i11.Response> Function()? request,
    T Function(Map<String, dynamic>)? fromJson,
    String? key, {
    bool? isRetry = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListWithRetry,
          [
            request,
            fromJson,
            key,
          ],
          {#isRetry: isRetry},
        ),
        returnValue: _i4.Future<List<T>>.value(<T>[]),
      ) as _i4.Future<List<T>>);

  @override
  _i4.Future<T> performLogin<T>({
    required String? endpoint,
    required Map<String, dynamic>? body,
    required T Function(Map<String, dynamic>)? fromJson,
    required _i4.Future<void> Function(T)? onSuccess,
    String? invalidCredentialsMessage = 'Неверный email или пароль',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performLogin,
          [],
          {
            #endpoint: endpoint,
            #body: body,
            #fromJson: fromJson,
            #onSuccess: onSuccess,
            #invalidCredentialsMessage: invalidCredentialsMessage,
          },
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #performLogin,
                  [],
                  {
                    #endpoint: endpoint,
                    #body: body,
                    #fromJson: fromJson,
                    #onSuccess: onSuccess,
                    #invalidCredentialsMessage: invalidCredentialsMessage,
                  },
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #performLogin,
                [],
                {
                  #endpoint: endpoint,
                  #body: body,
                  #fromJson: fromJson,
                  #onSuccess: onSuccess,
                  #invalidCredentialsMessage: invalidCredentialsMessage,
                },
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<void> performLogout({
    required String? endpoint,
    required _i4.Future<void> Function()? onComplete,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performLogout,
          [],
          {
            #endpoint: endpoint,
            #onComplete: onComplete,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TokenHandler<_i5.User> get managerTokens => (super.noSuchMethod(
        Invocation.getter(#managerTokens),
        returnValue: _FakeTokenHandler_35<_i5.User>(
          this,
          Invocation.getter(#managerTokens),
        ),
      ) as _i2.TokenHandler<_i5.User>);

  @override
  _i2.TokenHandler<_i5.ClientUser> get clientTokens => (super.noSuchMethod(
        Invocation.getter(#clientTokens),
        returnValue: _FakeTokenHandler_35<_i5.ClientUser>(
          this,
          Invocation.getter(#clientTokens),
        ),
      ) as _i2.TokenHandler<_i5.ClientUser>);

  @override
  _i2.TokenHandler<_i8.EmployeeUser> get employeeTokens => (super.noSuchMethod(
        Invocation.getter(#employeeTokens),
        returnValue: _FakeTokenHandler_35<_i8.EmployeeUser>(
          this,
          Invocation.getter(#employeeTokens),
        ),
      ) as _i2.TokenHandler<_i8.EmployeeUser>);

  @override
  _i4.Future<_i9.SharedPreferences> get prefs => (super.noSuchMethod(
        Invocation.getter(#prefs),
        returnValue:
            _i4.Future<_i9.SharedPreferences>.value(_FakeSharedPreferences_36(
          this,
          Invocation.getter(#prefs),
        )),
      ) as _i4.Future<_i9.SharedPreferences>);

  @override
  set managerTokens(_i2.TokenHandler<_i5.User>? value) => super.noSuchMethod(
        Invocation.setter(
          #managerTokens,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set clientTokens(_i2.TokenHandler<_i5.ClientUser>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #clientTokens,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set employeeTokens(_i2.TokenHandler<_i8.EmployeeUser>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #employeeTokens,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> migrateToSecureStorage() => (super.noSuchMethod(
        Invocation.method(
          #migrateToSecureStorage,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [
            accessToken,
            refreshToken,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> hasTokens() => (super.noSuchMethod(
        Invocation.method(
          #hasTokens,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> saveUser(_i5.User? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.User?> getUser() => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [],
        ),
        returnValue: _i4.Future<_i5.User?>.value(),
      ) as _i4.Future<_i5.User?>);

  @override
  _i4.Future<void> clearUser() => (super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveClientTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClientTokens,
          [
            accessToken,
            refreshToken,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getClientAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getClientAccessToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> getClientRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getClientRefreshToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> clearClientTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearClientTokens,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> hasClientTokens() => (super.noSuchMethod(
        Invocation.method(
          #hasClientTokens,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> saveClientUser(_i5.ClientUser? user) => (super.noSuchMethod(
        Invocation.method(
          #saveClientUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.ClientUser?> getClientUser() => (super.noSuchMethod(
        Invocation.method(
          #getClientUser,
          [],
        ),
        returnValue: _i4.Future<_i5.ClientUser?>.value(),
      ) as _i4.Future<_i5.ClientUser?>);

  @override
  _i4.Future<void> saveEmployeeTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEmployeeTokens,
          [
            accessToken,
            refreshToken,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getEmployeeAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getEmployeeAccessToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> getEmployeeRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getEmployeeRefreshToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> clearEmployeeTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearEmployeeTokens,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> hasEmployeeTokens() => (super.noSuchMethod(
        Invocation.method(
          #hasEmployeeTokens,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> saveEmployeeUser(_i8.EmployeeUser? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEmployeeUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i8.EmployeeUser?> getEmployeeUser() => (super.noSuchMethod(
        Invocation.method(
          #getEmployeeUser,
          [],
        ),
        returnValue: _i4.Future<_i8.EmployeeUser?>.value(),
      ) as _i4.Future<_i8.EmployeeUser?>);

  @override
  _i4.Future<void> saveAppMode(String? mode) => (super.noSuchMethod(
        Invocation.method(
          #saveAppMode,
          [mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getAppMode() => (super.noSuchMethod(
        Invocation.method(
          #getAppMode,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> clearAppMode() => (super.noSuchMethod(
        Invocation.method(
          #clearAppMode,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveThemeMode(String? mode) => (super.noSuchMethod(
        Invocation.method(
          #saveThemeMode,
          [mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #getThemeMode,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearManagerData() => (super.noSuchMethod(
        Invocation.method(
          #clearManagerData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearClientData() => (super.noSuchMethod(
        Invocation.method(
          #clearClientData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearEmployeeData() => (super.noSuchMethod(
        Invocation.method(
          #clearEmployeeData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i13.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String?> read(String? key) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [key],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> write(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
