// Mocks generated by Mockito 5.4.6 from annotations
// in clothing_dashboard/test/core/providers/app_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i9;

import 'package:clothing_dashboard/core/models/models.dart' as _i6;
import 'package:clothing_dashboard/core/services/api_service.dart' as _i3;
import 'package:clothing_dashboard/core/services/storage_service.dart' as _i2;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:shared_preferences/shared_preferences.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStorageService_0 extends _i1.SmartFake
    implements _i2.StorageService {
  _FakeStorageService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiException_1 extends _i1.SmartFake implements _i3.ApiException {
  _FakeApiException_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_3<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_4 extends _i1.SmartFake implements _i6.AuthResponse {
  _FakeAuthResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_5 extends _i1.SmartFake implements _i6.User {
  _FakeUser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrdersResponse_6 extends _i1.SmartFake
    implements _i6.OrdersResponse {
  _FakeOrdersResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrder_7 extends _i1.SmartFake implements _i6.Order {
  _FakeOrder_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_8 extends _i1.SmartFake implements _i6.Client {
  _FakeClient_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderModel_9 extends _i1.SmartFake implements _i6.OrderModel {
  _FakeOrderModel_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProcessStep_10 extends _i1.SmartFake implements _i6.ProcessStep {
  _FakeProcessStep_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmployee_11 extends _i1.SmartFake implements _i6.Employee {
  _FakeEmployee_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkLog_12 extends _i1.SmartFake implements _i6.WorkLog {
  _FakeWorkLog_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayroll_13 extends _i1.SmartFake implements _i6.Payroll {
  _FakePayroll_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAnalyticsDashboard_14 extends _i1.SmartFake
    implements _i6.AnalyticsDashboard {
  _FakeAnalyticsDashboard_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDashboardStats_15 extends _i1.SmartFake
    implements _i6.DashboardStats {
  _FakeDashboardStats_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransaction_16 extends _i1.SmartFake implements _i6.Transaction {
  _FakeTransaction_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFinanceReport_17 extends _i1.SmartFake implements _i6.FinanceReport {
  _FakeFinanceReport_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForecast_18 extends _i1.SmartFake implements _i6.Forecast {
  _FakeForecast_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBusinessInsights_19 extends _i1.SmartFake
    implements _i6.BusinessInsights {
  _FakeBusinessInsights_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMlReport_20 extends _i1.SmartFake implements _i6.MlReport {
  _FakeMlReport_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMlUsageInfo_21 extends _i1.SmartFake implements _i6.MlUsageInfo {
  _FakeMlUsageInfo_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResourceUsage_22 extends _i1.SmartFake implements _i6.ResourceUsage {
  _FakeResourceUsage_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubscription_23 extends _i1.SmartFake implements _i6.Subscription {
  _FakeSubscription_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderAssignment_24 extends _i1.SmartFake
    implements _i6.OrderAssignment {
  _FakeOrderAssignment_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTokenHandler_25<T> extends _i1.SmartFake
    implements _i2.TokenHandler<T> {
  _FakeTokenHandler_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_26 extends _i1.SmartFake
    implements _i7.SharedPreferences {
  _FakeSharedPreferences_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get logPrefix =>
      (super.noSuchMethod(
            Invocation.getter(#logPrefix),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#logPrefix),
            ),
          )
          as String);

  @override
  String get authRefreshEndpoint =>
      (super.noSuchMethod(
            Invocation.getter(#authRefreshEndpoint),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#authRefreshEndpoint),
            ),
          )
          as String);

  @override
  _i2.StorageService get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeStorageService_0(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i2.StorageService);

  @override
  _i5.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> saveTokens(String? accessToken, String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [accessToken, refreshToken]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearTokens, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i3.ApiException createException(
    String? message, {
    int? statusCode,
    dynamic data,
    bool? isNetworkError = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createException,
              [message],
              {
                #statusCode: statusCode,
                #data: data,
                #isNetworkError: isNetworkError,
              },
            ),
            returnValue: _FakeApiException_1(
              this,
              Invocation.method(
                #createException,
                [message],
                {
                  #statusCode: statusCode,
                  #data: data,
                  #isNetworkError: isNetworkError,
                },
              ),
            ),
          )
          as _i3.ApiException);

  @override
  void log(String? message) => super.noSuchMethod(
    Invocation.method(#log, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i4.Response> loggedGet(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loggedGet, [url], {#headers: headers}),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#loggedGet, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> loggedPost(
    Uri? url, {
    Map<String, String>? headers,
    dynamic body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loggedPost,
              [url],
              {#headers: headers, #body: body},
            ),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #loggedPost,
                  [url],
                  {#headers: headers, #body: body},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> loggedPut(
    Uri? url, {
    Map<String, String>? headers,
    dynamic body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loggedPut,
              [url],
              {#headers: headers, #body: body},
            ),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #loggedPut,
                  [url],
                  {#headers: headers, #body: body},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> loggedPatch(
    Uri? url, {
    Map<String, String>? headers,
    dynamic body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loggedPatch,
              [url],
              {#headers: headers, #body: body},
            ),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #loggedPatch,
                  [url],
                  {#headers: headers, #body: body},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> loggedDelete(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loggedDelete, [url], {#headers: headers}),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#loggedDelete, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<Map<String, String>> getHeaders({bool? auth = true}) =>
      (super.noSuchMethod(
            Invocation.method(#getHeaders, [], {#auth: auth}),
            returnValue: _i5.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i5.Future<Map<String, String>>);

  @override
  _i5.Future<T> withNetworkErrorHandling<T>(
    _i5.Future<T> Function()? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withNetworkErrorHandling, [request]),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#withNetworkErrorHandling, [request]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_3<T>(
                  this,
                  Invocation.method(#withNetworkErrorHandling, [request]),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<T> withRetry<T>(
    _i5.Future<T> Function()? request, {
    bool? isRetry = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#withRetry, [request], {#isRetry: isRetry}),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #withRetry,
                      [request],
                      {#isRetry: isRetry},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_3<T>(
                  this,
                  Invocation.method(#withRetry, [request], {#isRetry: isRetry}),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<bool> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<T> handleResponse<T>(
    _i4.Response? response,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleResponse, [response, fromJson]),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#handleResponse, [response, fromJson]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_3<T>(
                  this,
                  Invocation.method(#handleResponse, [response, fromJson]),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<List<T>> handleListResponse<T>(
    _i4.Response? response,
    T Function(Map<String, dynamic>)? fromJson, [
    String? key,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#handleListResponse, [response, fromJson, key]),
            returnValue: _i5.Future<List<T>>.value(<T>[]),
          )
          as _i5.Future<List<T>>);

  @override
  _i5.Future<List<T>> getListWithRetry<T>(
    _i5.Future<_i4.Response> Function()? request,
    T Function(Map<String, dynamic>)? fromJson,
    String? key, {
    bool? isRetry = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getListWithRetry,
              [request, fromJson, key],
              {#isRetry: isRetry},
            ),
            returnValue: _i5.Future<List<T>>.value(<T>[]),
          )
          as _i5.Future<List<T>>);

  @override
  _i5.Future<T> performLogin<T>({
    required String? endpoint,
    required Map<String, dynamic>? body,
    required T Function(Map<String, dynamic>)? fromJson,
    required _i5.Future<void> Function(T)? onSuccess,
    String? invalidCredentialsMessage = 'Неверный email или пароль',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#performLogin, [], {
              #endpoint: endpoint,
              #body: body,
              #fromJson: fromJson,
              #onSuccess: onSuccess,
              #invalidCredentialsMessage: invalidCredentialsMessage,
            }),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#performLogin, [], {
                      #endpoint: endpoint,
                      #body: body,
                      #fromJson: fromJson,
                      #onSuccess: onSuccess,
                      #invalidCredentialsMessage: invalidCredentialsMessage,
                    }),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_3<T>(
                  this,
                  Invocation.method(#performLogin, [], {
                    #endpoint: endpoint,
                    #body: body,
                    #fromJson: fromJson,
                    #onSuccess: onSuccess,
                    #invalidCredentialsMessage: invalidCredentialsMessage,
                  }),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<void> performLogout({
    required String? endpoint,
    required _i5.Future<void> Function()? onComplete,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#performLogout, [], {
              #endpoint: endpoint,
              #onComplete: onComplete,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.AuthResponse> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i5.Future<_i6.AuthResponse>.value(
              _FakeAuthResponse_4(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i5.Future<_i6.AuthResponse>);

  @override
  _i5.Future<_i6.AuthResponse> register(
    String? email,
    String? password,
    String? tenantName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password, tenantName]),
            returnValue: _i5.Future<_i6.AuthResponse>.value(
              _FakeAuthResponse_4(
                this,
                Invocation.method(#register, [email, password, tenantName]),
              ),
            ),
          )
          as _i5.Future<_i6.AuthResponse>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> changePassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [currentPassword, newPassword]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.User> uploadAvatar(_i9.File? file) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAvatar, [file]),
            returnValue: _i5.Future<_i6.User>.value(
              _FakeUser_5(this, Invocation.method(#uploadAvatar, [file])),
            ),
          )
          as _i5.Future<_i6.User>);

  @override
  _i5.Future<_i6.User> deleteAvatar() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAvatar, []),
            returnValue: _i5.Future<_i6.User>.value(
              _FakeUser_5(this, Invocation.method(#deleteAvatar, [])),
            ),
          )
          as _i5.Future<_i6.User>);

  @override
  _i5.Future<_i6.OrdersResponse> getOrders({
    int? page = 1,
    int? limit = 20,
    String? status,
    String? sortBy,
    String? sortOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrders, [], {
              #page: page,
              #limit: limit,
              #status: status,
              #sortBy: sortBy,
              #sortOrder: sortOrder,
            }),
            returnValue: _i5.Future<_i6.OrdersResponse>.value(
              _FakeOrdersResponse_6(
                this,
                Invocation.method(#getOrders, [], {
                  #page: page,
                  #limit: limit,
                  #status: status,
                  #sortBy: sortBy,
                  #sortOrder: sortOrder,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.OrdersResponse>);

  @override
  _i5.Future<_i6.Order> getOrder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getOrder, [id]),
            returnValue: _i5.Future<_i6.Order>.value(
              _FakeOrder_7(this, Invocation.method(#getOrder, [id])),
            ),
          )
          as _i5.Future<_i6.Order>);

  @override
  _i5.Future<_i6.Order> createOrder({
    required String? clientId,
    required String? modelId,
    required int? quantity,
    String? dueDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [], {
              #clientId: clientId,
              #modelId: modelId,
              #quantity: quantity,
              #dueDate: dueDate,
            }),
            returnValue: _i5.Future<_i6.Order>.value(
              _FakeOrder_7(
                this,
                Invocation.method(#createOrder, [], {
                  #clientId: clientId,
                  #modelId: modelId,
                  #quantity: quantity,
                  #dueDate: dueDate,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Order>);

  @override
  _i5.Future<_i6.Order> updateOrderStatus(String? id, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatus, [id, status]),
            returnValue: _i5.Future<_i6.Order>.value(
              _FakeOrder_7(
                this,
                Invocation.method(#updateOrderStatus, [id, status]),
              ),
            ),
          )
          as _i5.Future<_i6.Order>);

  @override
  _i5.Future<Map<String, dynamic>?> searchClientUserByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#searchClientUserByEmail, [email]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<List<_i6.Client>> getClients({int? page = 1, int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getClients, [], {#page: page, #limit: limit}),
            returnValue: _i5.Future<List<_i6.Client>>.value(<_i6.Client>[]),
          )
          as _i5.Future<List<_i6.Client>>);

  @override
  _i5.Future<_i6.Client> getClient(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getClient, [id]),
            returnValue: _i5.Future<_i6.Client>.value(
              _FakeClient_8(this, Invocation.method(#getClient, [id])),
            ),
          )
          as _i5.Future<_i6.Client>);

  @override
  _i5.Future<_i6.Client> createClient({
    required String? name,
    String? email,
    String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createClient, [], {
              #name: name,
              #email: email,
              #phone: phone,
            }),
            returnValue: _i5.Future<_i6.Client>.value(
              _FakeClient_8(
                this,
                Invocation.method(#createClient, [], {
                  #name: name,
                  #email: email,
                  #phone: phone,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Client>);

  @override
  _i5.Future<_i6.Client> updateClient({
    required String? id,
    String? name,
    String? phone,
    String? email,
    String? telegram,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateClient, [], {
              #id: id,
              #name: name,
              #phone: phone,
              #email: email,
              #telegram: telegram,
              #notes: notes,
            }),
            returnValue: _i5.Future<_i6.Client>.value(
              _FakeClient_8(
                this,
                Invocation.method(#updateClient, [], {
                  #id: id,
                  #name: name,
                  #phone: phone,
                  #email: email,
                  #telegram: telegram,
                  #notes: notes,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Client>);

  @override
  _i5.Future<void> deleteClient(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteClient, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.OrderModel>> getClientAssignedModels(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#getClientAssignedModels, [clientId]),
            returnValue: _i5.Future<List<_i6.OrderModel>>.value(
              <_i6.OrderModel>[],
            ),
          )
          as _i5.Future<List<_i6.OrderModel>>);

  @override
  _i5.Future<_i6.Client> assignModelsToClient(
    String? clientId,
    List<String>? modelIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#assignModelsToClient, [clientId, modelIds]),
            returnValue: _i5.Future<_i6.Client>.value(
              _FakeClient_8(
                this,
                Invocation.method(#assignModelsToClient, [clientId, modelIds]),
              ),
            ),
          )
          as _i5.Future<_i6.Client>);

  @override
  _i5.Future<_i6.Client> setClientAssignedModels(
    String? clientId,
    List<String>? modelIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setClientAssignedModels, [clientId, modelIds]),
            returnValue: _i5.Future<_i6.Client>.value(
              _FakeClient_8(
                this,
                Invocation.method(#setClientAssignedModels, [
                  clientId,
                  modelIds,
                ]),
              ),
            ),
          )
          as _i5.Future<_i6.Client>);

  @override
  _i5.Future<_i6.Client> unassignModelFromClient(
    String? clientId,
    String? modelId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#unassignModelFromClient, [clientId, modelId]),
            returnValue: _i5.Future<_i6.Client>.value(
              _FakeClient_8(
                this,
                Invocation.method(#unassignModelFromClient, [
                  clientId,
                  modelId,
                ]),
              ),
            ),
          )
          as _i5.Future<_i6.Client>);

  @override
  _i5.Future<List<_i6.OrderModel>> getModels({
    int? page = 1,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getModels, [], {#page: page, #limit: limit}),
            returnValue: _i5.Future<List<_i6.OrderModel>>.value(
              <_i6.OrderModel>[],
            ),
          )
          as _i5.Future<List<_i6.OrderModel>>);

  @override
  _i5.Future<_i6.OrderModel> getModel(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getModel, [id]),
            returnValue: _i5.Future<_i6.OrderModel>.value(
              _FakeOrderModel_9(this, Invocation.method(#getModel, [id])),
            ),
          )
          as _i5.Future<_i6.OrderModel>);

  @override
  _i5.Future<_i6.OrderModel> createModel({
    required String? name,
    String? category,
    required double? basePrice,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createModel, [], {
              #name: name,
              #category: category,
              #basePrice: basePrice,
              #description: description,
            }),
            returnValue: _i5.Future<_i6.OrderModel>.value(
              _FakeOrderModel_9(
                this,
                Invocation.method(#createModel, [], {
                  #name: name,
                  #category: category,
                  #basePrice: basePrice,
                  #description: description,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.OrderModel>);

  @override
  _i5.Future<_i6.OrderModel> updateModel({
    required String? id,
    String? name,
    String? category,
    double? basePrice,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateModel, [], {
              #id: id,
              #name: name,
              #category: category,
              #basePrice: basePrice,
              #description: description,
            }),
            returnValue: _i5.Future<_i6.OrderModel>.value(
              _FakeOrderModel_9(
                this,
                Invocation.method(#updateModel, [], {
                  #id: id,
                  #name: name,
                  #category: category,
                  #basePrice: basePrice,
                  #description: description,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.OrderModel>);

  @override
  _i5.Future<void> deleteModel(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteModel, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.OrderModel> uploadModelImage(
    String? modelId,
    _i9.File? file,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadModelImage, [modelId, file]),
            returnValue: _i5.Future<_i6.OrderModel>.value(
              _FakeOrderModel_9(
                this,
                Invocation.method(#uploadModelImage, [modelId, file]),
              ),
            ),
          )
          as _i5.Future<_i6.OrderModel>);

  @override
  _i5.Future<_i6.OrderModel> deleteModelImage(String? modelId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteModelImage, [modelId]),
            returnValue: _i5.Future<_i6.OrderModel>.value(
              _FakeOrderModel_9(
                this,
                Invocation.method(#deleteModelImage, [modelId]),
              ),
            ),
          )
          as _i5.Future<_i6.OrderModel>);

  @override
  _i5.Future<List<_i6.ProcessStep>> getProcessSteps(String? modelId) =>
      (super.noSuchMethod(
            Invocation.method(#getProcessSteps, [modelId]),
            returnValue: _i5.Future<List<_i6.ProcessStep>>.value(
              <_i6.ProcessStep>[],
            ),
          )
          as _i5.Future<List<_i6.ProcessStep>>);

  @override
  _i5.Future<_i6.ProcessStep> createProcessStep({
    required String? modelId,
    required int? stepOrder,
    required String? name,
    required int? estimatedTime,
    required String? executorRole,
    double? rate,
    String? rateType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createProcessStep, [], {
              #modelId: modelId,
              #stepOrder: stepOrder,
              #name: name,
              #estimatedTime: estimatedTime,
              #executorRole: executorRole,
              #rate: rate,
              #rateType: rateType,
            }),
            returnValue: _i5.Future<_i6.ProcessStep>.value(
              _FakeProcessStep_10(
                this,
                Invocation.method(#createProcessStep, [], {
                  #modelId: modelId,
                  #stepOrder: stepOrder,
                  #name: name,
                  #estimatedTime: estimatedTime,
                  #executorRole: executorRole,
                  #rate: rate,
                  #rateType: rateType,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.ProcessStep>);

  @override
  _i5.Future<_i6.ProcessStep> updateProcessStep({
    required String? stepId,
    int? stepOrder,
    String? name,
    int? estimatedTime,
    String? executorRole,
    double? rate,
    String? rateType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProcessStep, [], {
              #stepId: stepId,
              #stepOrder: stepOrder,
              #name: name,
              #estimatedTime: estimatedTime,
              #executorRole: executorRole,
              #rate: rate,
              #rateType: rateType,
            }),
            returnValue: _i5.Future<_i6.ProcessStep>.value(
              _FakeProcessStep_10(
                this,
                Invocation.method(#updateProcessStep, [], {
                  #stepId: stepId,
                  #stepOrder: stepOrder,
                  #name: name,
                  #estimatedTime: estimatedTime,
                  #executorRole: executorRole,
                  #rate: rate,
                  #rateType: rateType,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.ProcessStep>);

  @override
  _i5.Future<void> deleteProcessStep(String? stepId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProcessStep, [stepId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.EmployeeRole>> getEmployeeRoles() =>
      (super.noSuchMethod(
            Invocation.method(#getEmployeeRoles, []),
            returnValue: _i5.Future<List<_i6.EmployeeRole>>.value(
              <_i6.EmployeeRole>[],
            ),
          )
          as _i5.Future<List<_i6.EmployeeRole>>);

  @override
  _i5.Future<List<_i6.Employee>> getEmployees({
    int? page = 1,
    int? limit = 50,
    bool? isActive,
    String? role,
    String? sortBy,
    String? sortOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEmployees, [], {
              #page: page,
              #limit: limit,
              #isActive: isActive,
              #role: role,
              #sortBy: sortBy,
              #sortOrder: sortOrder,
            }),
            returnValue: _i5.Future<List<_i6.Employee>>.value(<_i6.Employee>[]),
          )
          as _i5.Future<List<_i6.Employee>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getEmployeeWorkLogs(
    String? employeeId, {
    String? dateFrom,
    String? dateTo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEmployeeWorkLogs,
              [employeeId],
              {#dateFrom: dateFrom, #dateTo: dateTo},
            ),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getAllWorklogs({
    String? employeeId,
    String? dateFrom,
    String? dateTo,
    String? step,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllWorklogs, [], {
              #employeeId: employeeId,
              #dateFrom: dateFrom,
              #dateTo: dateTo,
              #step: step,
            }),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>> getWorklogsSummary({
    String? employeeId,
    String? dateFrom,
    String? dateTo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWorklogsSummary, [], {
              #employeeId: employeeId,
              #dateFrom: dateFrom,
              #dateTo: dateTo,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i6.Employee> getEmployee(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEmployee, [id]),
            returnValue: _i5.Future<_i6.Employee>.value(
              _FakeEmployee_11(this, Invocation.method(#getEmployee, [id])),
            ),
          )
          as _i5.Future<_i6.Employee>);

  @override
  _i5.Future<_i6.Employee> createEmployee({
    required String? name,
    required String? role,
    String? phone,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEmployee, [], {
              #name: name,
              #role: role,
              #phone: phone,
              #email: email,
            }),
            returnValue: _i5.Future<_i6.Employee>.value(
              _FakeEmployee_11(
                this,
                Invocation.method(#createEmployee, [], {
                  #name: name,
                  #role: role,
                  #phone: phone,
                  #email: email,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Employee>);

  @override
  _i5.Future<_i6.Employee> updateEmployee({
    required String? id,
    String? name,
    String? role,
    String? phone,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmployee, [], {
              #id: id,
              #name: name,
              #role: role,
              #phone: phone,
              #email: email,
            }),
            returnValue: _i5.Future<_i6.Employee>.value(
              _FakeEmployee_11(
                this,
                Invocation.method(#updateEmployee, [], {
                  #id: id,
                  #name: name,
                  #role: role,
                  #phone: phone,
                  #email: email,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Employee>);

  @override
  _i5.Future<void> deleteEmployee(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmployee, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.WorkLog>> getWorkLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkLogs, []),
            returnValue: _i5.Future<List<_i6.WorkLog>>.value(<_i6.WorkLog>[]),
          )
          as _i5.Future<List<_i6.WorkLog>>);

  @override
  _i5.Future<_i6.WorkLog> createWorkLog({
    required String? employeeId,
    required String? orderId,
    required String? step,
    required int? quantity,
    required double? hours,
    required DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createWorkLog, [], {
              #employeeId: employeeId,
              #orderId: orderId,
              #step: step,
              #quantity: quantity,
              #hours: hours,
              #date: date,
            }),
            returnValue: _i5.Future<_i6.WorkLog>.value(
              _FakeWorkLog_12(
                this,
                Invocation.method(#createWorkLog, [], {
                  #employeeId: employeeId,
                  #orderId: orderId,
                  #step: step,
                  #quantity: quantity,
                  #hours: hours,
                  #date: date,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.WorkLog>);

  @override
  _i5.Future<List<_i6.Payroll>> getPayrolls() =>
      (super.noSuchMethod(
            Invocation.method(#getPayrolls, []),
            returnValue: _i5.Future<List<_i6.Payroll>>.value(<_i6.Payroll>[]),
          )
          as _i5.Future<List<_i6.Payroll>>);

  @override
  _i5.Future<_i6.Payroll> generatePayroll({
    required DateTime? periodStart,
    required DateTime? periodEnd,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generatePayroll, [], {
              #periodStart: periodStart,
              #periodEnd: periodEnd,
            }),
            returnValue: _i5.Future<_i6.Payroll>.value(
              _FakePayroll_13(
                this,
                Invocation.method(#generatePayroll, [], {
                  #periodStart: periodStart,
                  #periodEnd: periodEnd,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Payroll>);

  @override
  _i5.Future<_i6.AnalyticsDashboard> getAnalyticsDashboard({
    String? period = 'month',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAnalyticsDashboard, [], {#period: period}),
            returnValue: _i5.Future<_i6.AnalyticsDashboard>.value(
              _FakeAnalyticsDashboard_14(
                this,
                Invocation.method(#getAnalyticsDashboard, [], {
                  #period: period,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.AnalyticsDashboard>);

  @override
  _i5.Future<_i6.DashboardStats> getDashboardStats({
    String? period = 'month',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardStats, [], {#period: period}),
            returnValue: _i5.Future<_i6.DashboardStats>.value(
              _FakeDashboardStats_15(
                this,
                Invocation.method(#getDashboardStats, [], {#period: period}),
              ),
            ),
          )
          as _i5.Future<_i6.DashboardStats>);

  @override
  _i5.Future<Map<String, dynamic>> getWorkloadCalendar({
    int? days = 14,
    String? employeeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkloadCalendar, [], {
              #days: days,
              #employeeId: employeeId,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<_i6.Transaction>> getTransactions({
    String? type,
    String? startDate,
    String? endDate,
    int? page = 1,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, [], {
              #type: type,
              #startDate: startDate,
              #endDate: endDate,
              #page: page,
              #limit: limit,
            }),
            returnValue: _i5.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i5.Future<List<_i6.Transaction>>);

  @override
  _i5.Future<_i6.Transaction> createTransaction({
    required DateTime? date,
    required String? type,
    required String? category,
    required double? amount,
    String? description,
    String? orderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [], {
              #date: date,
              #type: type,
              #category: category,
              #amount: amount,
              #description: description,
              #orderId: orderId,
            }),
            returnValue: _i5.Future<_i6.Transaction>.value(
              _FakeTransaction_16(
                this,
                Invocation.method(#createTransaction, [], {
                  #date: date,
                  #type: type,
                  #category: category,
                  #amount: amount,
                  #description: description,
                  #orderId: orderId,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Transaction>);

  @override
  _i5.Future<void> deleteTransaction(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.FinanceReport> getFinanceReport({
    String? startDate,
    String? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFinanceReport, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i5.Future<_i6.FinanceReport>.value(
              _FakeFinanceReport_17(
                this,
                Invocation.method(#getFinanceReport, [], {
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.FinanceReport>);

  @override
  _i5.Future<_i6.Forecast> getOrdersForecast({int? days = 7}) =>
      (super.noSuchMethod(
            Invocation.method(#getOrdersForecast, [], {#days: days}),
            returnValue: _i5.Future<_i6.Forecast>.value(
              _FakeForecast_18(
                this,
                Invocation.method(#getOrdersForecast, [], {#days: days}),
              ),
            ),
          )
          as _i5.Future<_i6.Forecast>);

  @override
  _i5.Future<_i6.Forecast> getRevenueForecast({int? days = 7}) =>
      (super.noSuchMethod(
            Invocation.method(#getRevenueForecast, [], {#days: days}),
            returnValue: _i5.Future<_i6.Forecast>.value(
              _FakeForecast_18(
                this,
                Invocation.method(#getRevenueForecast, [], {#days: days}),
              ),
            ),
          )
          as _i5.Future<_i6.Forecast>);

  @override
  _i5.Future<_i6.BusinessInsights> getBusinessInsights() =>
      (super.noSuchMethod(
            Invocation.method(#getBusinessInsights, []),
            returnValue: _i5.Future<_i6.BusinessInsights>.value(
              _FakeBusinessInsights_19(
                this,
                Invocation.method(#getBusinessInsights, []),
              ),
            ),
          )
          as _i5.Future<_i6.BusinessInsights>);

  @override
  _i5.Future<_i6.MlReport> generateMlReport({
    required String? type,
    String? periodStart,
    String? periodEnd,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateMlReport, [], {
              #type: type,
              #periodStart: periodStart,
              #periodEnd: periodEnd,
            }),
            returnValue: _i5.Future<_i6.MlReport>.value(
              _FakeMlReport_20(
                this,
                Invocation.method(#generateMlReport, [], {
                  #type: type,
                  #periodStart: periodStart,
                  #periodEnd: periodEnd,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.MlReport>);

  @override
  _i5.Future<List<_i6.MlReport>> getReportHistory({
    String? type,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReportHistory, [], {
              #type: type,
              #limit: limit,
            }),
            returnValue: _i5.Future<List<_i6.MlReport>>.value(<_i6.MlReport>[]),
          )
          as _i5.Future<List<_i6.MlReport>>);

  @override
  _i5.Future<_i6.MlUsageInfo> getMlUsageInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getMlUsageInfo, []),
            returnValue: _i5.Future<_i6.MlUsageInfo>.value(
              _FakeMlUsageInfo_21(this, Invocation.method(#getMlUsageInfo, [])),
            ),
          )
          as _i5.Future<_i6.MlUsageInfo>);

  @override
  _i5.Future<List<_i6.SubscriptionPlan>> getSubscriptionPlans() =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptionPlans, []),
            returnValue: _i5.Future<List<_i6.SubscriptionPlan>>.value(
              <_i6.SubscriptionPlan>[],
            ),
          )
          as _i5.Future<List<_i6.SubscriptionPlan>>);

  @override
  _i5.Future<_i6.ResourceUsage> getResourceUsage() =>
      (super.noSuchMethod(
            Invocation.method(#getResourceUsage, []),
            returnValue: _i5.Future<_i6.ResourceUsage>.value(
              _FakeResourceUsage_22(
                this,
                Invocation.method(#getResourceUsage, []),
              ),
            ),
          )
          as _i5.Future<_i6.ResourceUsage>);

  @override
  _i5.Future<_i6.Subscription?> getCurrentSubscription() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentSubscription, []),
            returnValue: _i5.Future<_i6.Subscription?>.value(),
          )
          as _i5.Future<_i6.Subscription?>);

  @override
  _i5.Future<_i6.Subscription> verifyGooglePlayPurchase({
    required String? productId,
    required String? purchaseToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyGooglePlayPurchase, [], {
              #productId: productId,
              #purchaseToken: purchaseToken,
            }),
            returnValue: _i5.Future<_i6.Subscription>.value(
              _FakeSubscription_23(
                this,
                Invocation.method(#verifyGooglePlayPurchase, [], {
                  #productId: productId,
                  #purchaseToken: purchaseToken,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Subscription>);

  @override
  _i5.Future<_i6.Subscription> verifyAppStorePurchase({
    required String? receiptData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyAppStorePurchase, [], {
              #receiptData: receiptData,
            }),
            returnValue: _i5.Future<_i6.Subscription>.value(
              _FakeSubscription_23(
                this,
                Invocation.method(#verifyAppStorePurchase, [], {
                  #receiptData: receiptData,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Subscription>);

  @override
  _i5.Future<void> registerPushDevice(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#registerPushDevice, [playerId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> unregisterPushDevice() =>
      (super.noSuchMethod(
            Invocation.method(#unregisterPushDevice, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.OrderAssignment>> getOrderAssignments(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderAssignments, [orderId]),
            returnValue: _i5.Future<List<_i6.OrderAssignment>>.value(
              <_i6.OrderAssignment>[],
            ),
          )
          as _i5.Future<List<_i6.OrderAssignment>>);

  @override
  _i5.Future<_i6.OrderAssignment> createOrderAssignment({
    required String? orderId,
    required String? stepName,
    required String? employeeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOrderAssignment, [], {
              #orderId: orderId,
              #stepName: stepName,
              #employeeId: employeeId,
            }),
            returnValue: _i5.Future<_i6.OrderAssignment>.value(
              _FakeOrderAssignment_24(
                this,
                Invocation.method(#createOrderAssignment, [], {
                  #orderId: orderId,
                  #stepName: stepName,
                  #employeeId: employeeId,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.OrderAssignment>);

  @override
  _i5.Future<void> deleteOrderAssignment(
    String? orderId,
    String? assignmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrderAssignment, [orderId, assignmentId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TokenHandler<_i6.User> get managerTokens =>
      (super.noSuchMethod(
            Invocation.getter(#managerTokens),
            returnValue: _FakeTokenHandler_25<_i6.User>(
              this,
              Invocation.getter(#managerTokens),
            ),
          )
          as _i2.TokenHandler<_i6.User>);

  @override
  _i2.TokenHandler<_i6.ClientUser> get clientTokens =>
      (super.noSuchMethod(
            Invocation.getter(#clientTokens),
            returnValue: _FakeTokenHandler_25<_i6.ClientUser>(
              this,
              Invocation.getter(#clientTokens),
            ),
          )
          as _i2.TokenHandler<_i6.ClientUser>);

  @override
  _i2.TokenHandler<_i6.EmployeeUser> get employeeTokens =>
      (super.noSuchMethod(
            Invocation.getter(#employeeTokens),
            returnValue: _FakeTokenHandler_25<_i6.EmployeeUser>(
              this,
              Invocation.getter(#employeeTokens),
            ),
          )
          as _i2.TokenHandler<_i6.EmployeeUser>);

  @override
  _i5.Future<_i7.SharedPreferences> get prefs =>
      (super.noSuchMethod(
            Invocation.getter(#prefs),
            returnValue: _i5.Future<_i7.SharedPreferences>.value(
              _FakeSharedPreferences_26(this, Invocation.getter(#prefs)),
            ),
          )
          as _i5.Future<_i7.SharedPreferences>);

  @override
  set managerTokens(_i2.TokenHandler<_i6.User>? value) => super.noSuchMethod(
    Invocation.setter(#managerTokens, value),
    returnValueForMissingStub: null,
  );

  @override
  set clientTokens(_i2.TokenHandler<_i6.ClientUser>? value) =>
      super.noSuchMethod(
        Invocation.setter(#clientTokens, value),
        returnValueForMissingStub: null,
      );

  @override
  set employeeTokens(_i2.TokenHandler<_i6.EmployeeUser>? value) =>
      super.noSuchMethod(
        Invocation.setter(#employeeTokens, value),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> migrateToSecureStorage() =>
      (super.noSuchMethod(
            Invocation.method(#migrateToSecureStorage, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveTokens(String? accessToken, String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [accessToken, refreshToken]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> clearTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearTokens, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> hasTokens() =>
      (super.noSuchMethod(
            Invocation.method(#hasTokens, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> saveUser(_i6.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.User?> getUser() =>
      (super.noSuchMethod(
            Invocation.method(#getUser, []),
            returnValue: _i5.Future<_i6.User?>.value(),
          )
          as _i5.Future<_i6.User?>);

  @override
  _i5.Future<void> clearUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearUser, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveClientTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveClientTokens, [accessToken, refreshToken]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getClientAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getClientAccessToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> getClientRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getClientRefreshToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> clearClientTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearClientTokens, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> hasClientTokens() =>
      (super.noSuchMethod(
            Invocation.method(#hasClientTokens, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> saveClientUser(_i6.ClientUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveClientUser, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.ClientUser?> getClientUser() =>
      (super.noSuchMethod(
            Invocation.method(#getClientUser, []),
            returnValue: _i5.Future<_i6.ClientUser?>.value(),
          )
          as _i5.Future<_i6.ClientUser?>);

  @override
  _i5.Future<void> saveEmployeeTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveEmployeeTokens, [accessToken, refreshToken]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getEmployeeAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getEmployeeAccessToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> getEmployeeRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getEmployeeRefreshToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> clearEmployeeTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearEmployeeTokens, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> hasEmployeeTokens() =>
      (super.noSuchMethod(
            Invocation.method(#hasEmployeeTokens, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> saveEmployeeUser(_i6.EmployeeUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveEmployeeUser, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.EmployeeUser?> getEmployeeUser() =>
      (super.noSuchMethod(
            Invocation.method(#getEmployeeUser, []),
            returnValue: _i5.Future<_i6.EmployeeUser?>.value(),
          )
          as _i5.Future<_i6.EmployeeUser?>);

  @override
  _i5.Future<void> saveAppMode(String? mode) =>
      (super.noSuchMethod(
            Invocation.method(#saveAppMode, [mode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getAppMode() =>
      (super.noSuchMethod(
            Invocation.method(#getAppMode, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> clearAppMode() =>
      (super.noSuchMethod(
            Invocation.method(#clearAppMode, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveThemeMode(String? mode) =>
      (super.noSuchMethod(
            Invocation.method(#saveThemeMode, [mode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> getThemeMode() =>
      (super.noSuchMethod(
            Invocation.method(#getThemeMode, []),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getThemeMode, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearManagerData() =>
      (super.noSuchMethod(
            Invocation.method(#clearManagerData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearClientData() =>
      (super.noSuchMethod(
            Invocation.method(#clearClientData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearEmployeeData() =>
      (super.noSuchMethod(
            Invocation.method(#clearEmployeeData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
