// Mocks generated by Mockito 5.4.6 from annotations
// in clothing_dashboard/test/core/providers/client_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:clothing_dashboard/core/models/employee_user.dart' as _i8;
import 'package:clothing_dashboard/core/models/models.dart' as _i5;
import 'package:clothing_dashboard/core/services/client_api_service.dart'
    as _i4;
import 'package:clothing_dashboard/core/services/storage_service.dart' as _i2;
import 'package:http/http.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:shared_preferences/shared_preferences.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTokenHandler_0<T> extends _i1.SmartFake
    implements _i2.TokenHandler<T> {
  _FakeTokenHandler_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_1 extends _i1.SmartFake
    implements _i3.SharedPreferences {
  _FakeSharedPreferences_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageService_2 extends _i1.SmartFake
    implements _i2.StorageService {
  _FakeStorageService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientApiException_3 extends _i1.SmartFake
    implements _i4.ClientApiException {
  _FakeClientApiException_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientAuthResponse_4 extends _i1.SmartFake
    implements _i5.ClientAuthResponse {
  _FakeClientAuthResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientUser_5 extends _i1.SmartFake implements _i5.ClientUser {
  _FakeClientUser_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTenantLink_6 extends _i1.SmartFake implements _i5.TenantLink {
  _FakeTenantLink_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientOrdersResponse_7 extends _i1.SmartFake
    implements _i5.ClientOrdersResponse {
  _FakeClientOrdersResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientOrder_8 extends _i1.SmartFake implements _i5.ClientOrder {
  _FakeClientOrder_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_9 extends _i1.SmartFake implements _i6.Response {
  _FakeResponse_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_10<T1> extends _i1.SmartFake implements _i7.Future<T1> {
  _FakeFuture_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TokenHandler<_i5.User> get managerTokens => (super.noSuchMethod(
        Invocation.getter(#managerTokens),
        returnValue: _FakeTokenHandler_0<_i5.User>(
          this,
          Invocation.getter(#managerTokens),
        ),
      ) as _i2.TokenHandler<_i5.User>);

  @override
  _i2.TokenHandler<_i5.ClientUser> get clientTokens => (super.noSuchMethod(
        Invocation.getter(#clientTokens),
        returnValue: _FakeTokenHandler_0<_i5.ClientUser>(
          this,
          Invocation.getter(#clientTokens),
        ),
      ) as _i2.TokenHandler<_i5.ClientUser>);

  @override
  _i2.TokenHandler<_i8.EmployeeUser> get employeeTokens => (super.noSuchMethod(
        Invocation.getter(#employeeTokens),
        returnValue: _FakeTokenHandler_0<_i8.EmployeeUser>(
          this,
          Invocation.getter(#employeeTokens),
        ),
      ) as _i2.TokenHandler<_i8.EmployeeUser>);

  @override
  _i7.Future<_i3.SharedPreferences> get prefs => (super.noSuchMethod(
        Invocation.getter(#prefs),
        returnValue:
            _i7.Future<_i3.SharedPreferences>.value(_FakeSharedPreferences_1(
          this,
          Invocation.getter(#prefs),
        )),
      ) as _i7.Future<_i3.SharedPreferences>);

  @override
  set managerTokens(_i2.TokenHandler<_i5.User>? value) => super.noSuchMethod(
        Invocation.setter(
          #managerTokens,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set clientTokens(_i2.TokenHandler<_i5.ClientUser>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #clientTokens,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set employeeTokens(_i2.TokenHandler<_i8.EmployeeUser>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #employeeTokens,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> migrateToSecureStorage() => (super.noSuchMethod(
        Invocation.method(
          #migrateToSecureStorage,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [
            accessToken,
            refreshToken,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> hasTokens() => (super.noSuchMethod(
        Invocation.method(
          #hasTokens,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> saveUser(_i5.User? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.User?> getUser() => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [],
        ),
        returnValue: _i7.Future<_i5.User?>.value(),
      ) as _i7.Future<_i5.User?>);

  @override
  _i7.Future<void> clearUser() => (super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveClientTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClientTokens,
          [
            accessToken,
            refreshToken,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getClientAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getClientAccessToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getClientRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getClientRefreshToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> clearClientTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearClientTokens,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> hasClientTokens() => (super.noSuchMethod(
        Invocation.method(
          #hasClientTokens,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> saveClientUser(_i5.ClientUser? user) => (super.noSuchMethod(
        Invocation.method(
          #saveClientUser,
          [user],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.ClientUser?> getClientUser() => (super.noSuchMethod(
        Invocation.method(
          #getClientUser,
          [],
        ),
        returnValue: _i7.Future<_i5.ClientUser?>.value(),
      ) as _i7.Future<_i5.ClientUser?>);

  @override
  _i7.Future<void> saveEmployeeTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEmployeeTokens,
          [
            accessToken,
            refreshToken,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getEmployeeAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getEmployeeAccessToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getEmployeeRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getEmployeeRefreshToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> clearEmployeeTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearEmployeeTokens,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> hasEmployeeTokens() => (super.noSuchMethod(
        Invocation.method(
          #hasEmployeeTokens,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> saveEmployeeUser(_i8.EmployeeUser? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEmployeeUser,
          [user],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i8.EmployeeUser?> getEmployeeUser() => (super.noSuchMethod(
        Invocation.method(
          #getEmployeeUser,
          [],
        ),
        returnValue: _i7.Future<_i8.EmployeeUser?>.value(),
      ) as _i7.Future<_i8.EmployeeUser?>);

  @override
  _i7.Future<void> saveAppMode(String? mode) => (super.noSuchMethod(
        Invocation.method(
          #saveAppMode,
          [mode],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getAppMode() => (super.noSuchMethod(
        Invocation.method(
          #getAppMode,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> clearAppMode() => (super.noSuchMethod(
        Invocation.method(
          #clearAppMode,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveThemeMode(String? mode) => (super.noSuchMethod(
        Invocation.method(
          #saveThemeMode,
          [mode],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String> getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getThemeMode,
            [],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearManagerData() => (super.noSuchMethod(
        Invocation.method(
          #clearManagerData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearClientData() => (super.noSuchMethod(
        Invocation.method(
          #clearClientData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearEmployeeData() => (super.noSuchMethod(
        Invocation.method(
          #clearEmployeeData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [ClientApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientApiService extends _i1.Mock implements _i4.ClientApiService {
  MockClientApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get logPrefix => (super.noSuchMethod(
        Invocation.getter(#logPrefix),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#logPrefix),
        ),
      ) as String);

  @override
  String get authRefreshEndpoint => (super.noSuchMethod(
        Invocation.getter(#authRefreshEndpoint),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#authRefreshEndpoint),
        ),
      ) as String);

  @override
  _i2.StorageService get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeStorageService_2(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i2.StorageService);

  @override
  _i7.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> saveTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [
            accessToken,
            refreshToken,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i4.ClientApiException createException(
    String? message, {
    int? statusCode,
    dynamic data,
    bool? isNetworkError = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createException,
          [message],
          {
            #statusCode: statusCode,
            #data: data,
            #isNetworkError: isNetworkError,
          },
        ),
        returnValue: _FakeClientApiException_3(
          this,
          Invocation.method(
            #createException,
            [message],
            {
              #statusCode: statusCode,
              #data: data,
              #isNetworkError: isNetworkError,
            },
          ),
        ),
      ) as _i4.ClientApiException);

  @override
  _i7.Future<_i5.ClientAuthResponse> login({
    String? email,
    String? phone,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #phone: phone,
            #password: password,
          },
        ),
        returnValue:
            _i7.Future<_i5.ClientAuthResponse>.value(_FakeClientAuthResponse_4(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
            },
          ),
        )),
      ) as _i7.Future<_i5.ClientAuthResponse>);

  @override
  _i7.Future<_i5.ClientAuthResponse> register({
    String? email,
    String? phone,
    required String? password,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #email: email,
            #phone: phone,
            #password: password,
            #name: name,
          },
        ),
        returnValue:
            _i7.Future<_i5.ClientAuthResponse>.value(_FakeClientAuthResponse_4(
          this,
          Invocation.method(
            #register,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
              #name: name,
            },
          ),
        )),
      ) as _i7.Future<_i5.ClientAuthResponse>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.ClientUser> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i7.Future<_i5.ClientUser>.value(_FakeClientUser_5(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i7.Future<_i5.ClientUser>);

  @override
  _i7.Future<List<_i5.TenantLink>> getMyTenants() => (super.noSuchMethod(
        Invocation.method(
          #getMyTenants,
          [],
        ),
        returnValue: _i7.Future<List<_i5.TenantLink>>.value(<_i5.TenantLink>[]),
      ) as _i7.Future<List<_i5.TenantLink>>);

  @override
  _i7.Future<_i5.TenantLink> linkToTenant(
    String? tenantId, {
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkToTenant,
          [tenantId],
          {#name: name},
        ),
        returnValue: _i7.Future<_i5.TenantLink>.value(_FakeTenantLink_6(
          this,
          Invocation.method(
            #linkToTenant,
            [tenantId],
            {#name: name},
          ),
        )),
      ) as _i7.Future<_i5.TenantLink>);

  @override
  _i7.Future<List<_i5.ClientOrderModel>> getTenantModels(String? tenantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTenantModels,
          [tenantId],
        ),
        returnValue: _i7.Future<List<_i5.ClientOrderModel>>.value(
            <_i5.ClientOrderModel>[]),
      ) as _i7.Future<List<_i5.ClientOrderModel>>);

  @override
  _i7.Future<_i5.ClientOrdersResponse> getMyOrders({
    String? tenantId,
    int? page = 1,
    int? limit = 20,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyOrders,
          [],
          {
            #tenantId: tenantId,
            #page: page,
            #limit: limit,
            #status: status,
          },
        ),
        returnValue: _i7.Future<_i5.ClientOrdersResponse>.value(
            _FakeClientOrdersResponse_7(
          this,
          Invocation.method(
            #getMyOrders,
            [],
            {
              #tenantId: tenantId,
              #page: page,
              #limit: limit,
              #status: status,
            },
          ),
        )),
      ) as _i7.Future<_i5.ClientOrdersResponse>);

  @override
  _i7.Future<_i5.ClientOrder> getOrder(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #getOrder,
          [orderId],
        ),
        returnValue: _i7.Future<_i5.ClientOrder>.value(_FakeClientOrder_8(
          this,
          Invocation.method(
            #getOrder,
            [orderId],
          ),
        )),
      ) as _i7.Future<_i5.ClientOrder>);

  @override
  _i7.Future<_i5.ClientOrder> createOrder({
    required String? tenantId,
    required String? modelId,
    required int? quantity,
    String? dueDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [],
          {
            #tenantId: tenantId,
            #modelId: modelId,
            #quantity: quantity,
            #dueDate: dueDate,
          },
        ),
        returnValue: _i7.Future<_i5.ClientOrder>.value(_FakeClientOrder_8(
          this,
          Invocation.method(
            #createOrder,
            [],
            {
              #tenantId: tenantId,
              #modelId: modelId,
              #quantity: quantity,
              #dueDate: dueDate,
            },
          ),
        )),
      ) as _i7.Future<_i5.ClientOrder>);

  @override
  _i7.Future<_i5.ClientOrder> updateOrder({
    required String? orderId,
    String? modelId,
    int? quantity,
    String? dueDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrder,
          [],
          {
            #orderId: orderId,
            #modelId: modelId,
            #quantity: quantity,
            #dueDate: dueDate,
          },
        ),
        returnValue: _i7.Future<_i5.ClientOrder>.value(_FakeClientOrder_8(
          this,
          Invocation.method(
            #updateOrder,
            [],
            {
              #orderId: orderId,
              #modelId: modelId,
              #quantity: quantity,
              #dueDate: dueDate,
            },
          ),
        )),
      ) as _i7.Future<_i5.ClientOrder>);

  @override
  _i7.Future<void> cancelOrder(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #cancelOrder,
          [orderId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void log(String? message) => super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i6.Response> loggedGet(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loggedGet,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i6.Response>.value(_FakeResponse_9(
          this,
          Invocation.method(
            #loggedGet,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<_i6.Response>);

  @override
  _i7.Future<_i6.Response> loggedPost(
    Uri? url, {
    Map<String, String>? headers,
    dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loggedPost,
          [url],
          {
            #headers: headers,
            #body: body,
          },
        ),
        returnValue: _i7.Future<_i6.Response>.value(_FakeResponse_9(
          this,
          Invocation.method(
            #loggedPost,
            [url],
            {
              #headers: headers,
              #body: body,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response>);

  @override
  _i7.Future<_i6.Response> loggedPut(
    Uri? url, {
    Map<String, String>? headers,
    dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loggedPut,
          [url],
          {
            #headers: headers,
            #body: body,
          },
        ),
        returnValue: _i7.Future<_i6.Response>.value(_FakeResponse_9(
          this,
          Invocation.method(
            #loggedPut,
            [url],
            {
              #headers: headers,
              #body: body,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response>);

  @override
  _i7.Future<_i6.Response> loggedPatch(
    Uri? url, {
    Map<String, String>? headers,
    dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loggedPatch,
          [url],
          {
            #headers: headers,
            #body: body,
          },
        ),
        returnValue: _i7.Future<_i6.Response>.value(_FakeResponse_9(
          this,
          Invocation.method(
            #loggedPatch,
            [url],
            {
              #headers: headers,
              #body: body,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response>);

  @override
  _i7.Future<_i6.Response> loggedDelete(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loggedDelete,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i6.Response>.value(_FakeResponse_9(
          this,
          Invocation.method(
            #loggedDelete,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<_i6.Response>);

  @override
  _i7.Future<Map<String, String>> getHeaders({bool? auth = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHeaders,
          [],
          {#auth: auth},
        ),
        returnValue: _i7.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i7.Future<Map<String, String>>);

  @override
  _i7.Future<T> withNetworkErrorHandling<T>(
          _i7.Future<T> Function()? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #withNetworkErrorHandling,
          [request],
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #withNetworkErrorHandling,
                  [request],
                ),
              ),
              (T v) => _i7.Future<T>.value(v),
            ) ??
            _FakeFuture_10<T>(
              this,
              Invocation.method(
                #withNetworkErrorHandling,
                [request],
              ),
            ),
      ) as _i7.Future<T>);

  @override
  _i7.Future<T> withRetry<T>(
    _i7.Future<T> Function()? request, {
    bool? isRetry = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #withRetry,
          [request],
          {#isRetry: isRetry},
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #withRetry,
                  [request],
                  {#isRetry: isRetry},
                ),
              ),
              (T v) => _i7.Future<T>.value(v),
            ) ??
            _FakeFuture_10<T>(
              this,
              Invocation.method(
                #withRetry,
                [request],
                {#isRetry: isRetry},
              ),
            ),
      ) as _i7.Future<T>);

  @override
  _i7.Future<bool> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<T> handleResponse<T>(
    _i6.Response? response,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleResponse,
          [
            response,
            fromJson,
          ],
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #handleResponse,
                  [
                    response,
                    fromJson,
                  ],
                ),
              ),
              (T v) => _i7.Future<T>.value(v),
            ) ??
            _FakeFuture_10<T>(
              this,
              Invocation.method(
                #handleResponse,
                [
                  response,
                  fromJson,
                ],
              ),
            ),
      ) as _i7.Future<T>);

  @override
  _i7.Future<List<T>> handleListResponse<T>(
    _i6.Response? response,
    T Function(Map<String, dynamic>)? fromJson, [
    String? key,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleListResponse,
          [
            response,
            fromJson,
            key,
          ],
        ),
        returnValue: _i7.Future<List<T>>.value(<T>[]),
      ) as _i7.Future<List<T>>);

  @override
  _i7.Future<List<T>> getListWithRetry<T>(
    _i7.Future<_i6.Response> Function()? request,
    T Function(Map<String, dynamic>)? fromJson,
    String? key, {
    bool? isRetry = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListWithRetry,
          [
            request,
            fromJson,
            key,
          ],
          {#isRetry: isRetry},
        ),
        returnValue: _i7.Future<List<T>>.value(<T>[]),
      ) as _i7.Future<List<T>>);

  @override
  _i7.Future<T> performLogin<T>({
    required String? endpoint,
    required Map<String, dynamic>? body,
    required T Function(Map<String, dynamic>)? fromJson,
    required _i7.Future<void> Function(T)? onSuccess,
    String? invalidCredentialsMessage = 'Неверный email или пароль',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performLogin,
          [],
          {
            #endpoint: endpoint,
            #body: body,
            #fromJson: fromJson,
            #onSuccess: onSuccess,
            #invalidCredentialsMessage: invalidCredentialsMessage,
          },
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #performLogin,
                  [],
                  {
                    #endpoint: endpoint,
                    #body: body,
                    #fromJson: fromJson,
                    #onSuccess: onSuccess,
                    #invalidCredentialsMessage: invalidCredentialsMessage,
                  },
                ),
              ),
              (T v) => _i7.Future<T>.value(v),
            ) ??
            _FakeFuture_10<T>(
              this,
              Invocation.method(
                #performLogin,
                [],
                {
                  #endpoint: endpoint,
                  #body: body,
                  #fromJson: fromJson,
                  #onSuccess: onSuccess,
                  #invalidCredentialsMessage: invalidCredentialsMessage,
                },
              ),
            ),
      ) as _i7.Future<T>);

  @override
  _i7.Future<void> performLogout({
    required String? endpoint,
    required _i7.Future<void> Function()? onComplete,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performLogout,
          [],
          {
            #endpoint: endpoint,
            #onComplete: onComplete,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
